import type { CatalogEntry } from "./types";

// Lot pertinent — métiers spécifiques.
export const CATALOG_PLUS_1: CatalogEntry[] = [
  { id: "px1-notaire-campagne", label: "Devenir notaire de campagne", keywords: ["notaire", "campagne", "office", "rural"], oddsDenominator: 800, category: "metier", estimate: true },
  { id: "px1-notaire-ville", label: "Devenir notaire en ville", keywords: ["notaire", "ville", "office", "urbain"], oddsDenominator: 1200, category: "metier", estimate: true },
  { id: "px1-notaire-associe", label: "Devenir notaire associe dans une grande etude", keywords: ["notaire", "associe", "etude", "grande"], oddsDenominator: 2500, category: "metier", estimate: true },
  { id: "px1-chirurgien-esthetique", label: "Devenir chirurgien esthetique", keywords: ["chirurgien", "esthetique", "clinique", "operation"], oddsDenominator: 1500, category: "metier", estimate: true },
  { id: "px1-chirurgien-esthetique-cabinet", label: "Ouvrir un cabinet de chirurgie esthetique reconnu", keywords: ["chirurgien", "esthetique", "cabinet", "clinique"], oddsDenominator: 3000, category: "metier", estimate: true },
  { id: "px1-sage-femme-liberale", label: "Devenir sage-femme liberale", keywords: ["sage", "femme", "liberale", "naissance"], oddsDenominator: 200, category: "metier", estimate: true },
  { id: "px1-sage-femme-hopital", label: "Devenir sage-femme a l'hopital", keywords: ["sage", "femme", "hopital", "maternite"], oddsDenominator: 120, category: "metier", estimate: true },
  { id: "px1-osteopathe", label: "Devenir osteopathe en cabinet", keywords: ["osteopathe", "cabinet", "manipulation", "dos"], oddsDenominator: 150, category: "metier", estimate: true },
  { id: "px1-osteopathe-equin", label: "Devenir osteopathe equin", keywords: ["osteopathe", "equin", "cheval", "animal"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-sophrologue", label: "Devenir sophrologue installe", keywords: ["sophrologue", "relaxation", "respiration", "cabinet"], oddsDenominator: 250, category: "metier", estimate: true },
  { id: "px1-geobiologue", label: "Devenir geobiologue", keywords: ["geobiologue", "energie", "lieu", "habitat"], oddsDenominator: 600, category: "metier", estimate: true },
  { id: "px1-joaillier", label: "Devenir joaillier", keywords: ["joaillier", "bijou", "or", "pierre"], oddsDenominator: 700, category: "metier", estimate: true },
  { id: "px1-joaillier-luxe", label: "Devenir joaillier de luxe place Vendome", keywords: ["joaillier", "luxe", "vendome", "haute"], oddsDenominator: 5000, category: "metier", estimate: true },
  { id: "px1-antiquaire", label: "Devenir antiquaire", keywords: ["antiquaire", "ancien", "meuble", "brocante"], oddsDenominator: 500, category: "metier", estimate: true },
  { id: "px1-horloger", label: "Devenir horloger reparateur", keywords: ["horloger", "montre", "horloge", "reparation"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-horloger-haute", label: "Devenir horloger de haute horlogerie", keywords: ["horloger", "haute", "complication", "suisse"], oddsDenominator: 2000, category: "metier", estimate: true },
  { id: "px1-encadreur", label: "Devenir encadreur", keywords: ["encadreur", "cadre", "tableau", "atelier"], oddsDenominator: 300, category: "metier", estimate: true },
  { id: "px1-restaurateur-art", label: "Devenir restaurateur d'oeuvres d'art", keywords: ["restaurateur", "art", "oeuvre", "tableau"], oddsDenominator: 900, category: "metier", estimate: true },
  { id: "px1-fromager-affineur", label: "Devenir fromager affineur", keywords: ["fromager", "affineur", "fromage", "cave"], oddsDenominator: 350, category: "metier", estimate: true },
  { id: "px1-patissier-chocolatier", label: "Devenir patissier chocolatier", keywords: ["patissier", "chocolatier", "chocolat", "gateau"], oddsDenominator: 300, category: "metier", estimate: true },
  { id: "px1-maitre-brasseur", label: "Devenir maitre brasseur", keywords: ["brasseur", "biere", "brasserie", "houblon"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-vigneron-bio", label: "Devenir vigneron bio", keywords: ["vigneron", "bio", "vin", "vigne"], oddsDenominator: 500, category: "metier", estimate: true },
  { id: "px1-vigneron-grand-cru", label: "Devenir vigneron d'un grand cru", keywords: ["vigneron", "cru", "vin", "prestige"], oddsDenominator: 4000, category: "metier", estimate: true },
  { id: "px1-apiculteur", label: "Devenir apiculteur professionnel", keywords: ["apiculteur", "abeille", "miel", "ruche"], oddsDenominator: 250, category: "metier", estimate: true },
  { id: "px1-fauconnier", label: "Devenir fauconnier", keywords: ["fauconnier", "faucon", "rapace", "vol"], oddsDenominator: 1500, category: "metier", estimate: true },
  { id: "px1-dresseur-chevaux", label: "Devenir dresseur de chevaux", keywords: ["dresseur", "cheval", "equitation", "dressage"], oddsDenominator: 600, category: "metier", estimate: true },
  { id: "px1-marechal-ferrant", label: "Devenir marechal-ferrant", keywords: ["marechal", "ferrant", "cheval", "fer"], oddsDenominator: 300, category: "metier", estimate: true },
  { id: "px1-elagueur", label: "Devenir elagueur grimpeur", keywords: ["elagueur", "arbre", "grimpeur", "taille"], oddsDenominator: 200, category: "metier", estimate: true },
  { id: "px1-couvreur-zingueur", label: "Devenir couvreur-zingueur", keywords: ["couvreur", "zingueur", "toit", "toiture"], oddsDenominator: 150, category: "metier", estimate: true },
  { id: "px1-ebeniste", label: "Devenir ebeniste", keywords: ["ebeniste", "bois", "meuble", "atelier"], oddsDenominator: 300, category: "metier", estimate: true },
  { id: "px1-tapissier", label: "Devenir tapissier d'ameublement", keywords: ["tapissier", "ameublement", "fauteuil", "tissu"], oddsDenominator: 350, category: "metier", estimate: true },
  { id: "px1-luthier", label: "Devenir luthier", keywords: ["luthier", "violon", "guitare", "instrument"], oddsDenominator: 1200, category: "metier", estimate: true },
  { id: "px1-souffleur-verre", label: "Devenir souffleur de verre", keywords: ["souffleur", "verre", "verrerie", "feu"], oddsDenominator: 800, category: "metier", estimate: true },
  { id: "px1-ceramiste", label: "Devenir ceramiste", keywords: ["ceramiste", "ceramique", "terre", "tour"], oddsDenominator: 400, category: "artiste", estimate: true },
  { id: "px1-maroquinier", label: "Devenir maroquinier", keywords: ["maroquinier", "cuir", "sac", "atelier"], oddsDenominator: 450, category: "metier", estimate: true },
  { id: "px1-cordonnier", label: "Devenir cordonnier", keywords: ["cordonnier", "chaussure", "cuir", "reparation"], oddsDenominator: 200, category: "metier", estimate: true },
  { id: "px1-tailleur-pierre", label: "Devenir tailleur de pierre", keywords: ["tailleur", "pierre", "taille", "monument"], oddsDenominator: 300, category: "metier", estimate: true },
  { id: "px1-charpentier-marine", label: "Devenir charpentier de marine", keywords: ["charpentier", "marine", "bateau", "bois"], oddsDenominator: 900, category: "metier", estimate: true },
  { id: "px1-scaphandrier", label: "Devenir scaphandrier", keywords: ["scaphandrier", "plongee", "soudure", "sous-marin"], oddsDenominator: 700, category: "metier", estimate: true },
  { id: "px1-pisciculteur", label: "Devenir pisciculteur", keywords: ["pisciculteur", "poisson", "elevage", "bassin"], oddsDenominator: 350, category: "metier", estimate: true },
  { id: "px1-ostreiculteur", label: "Devenir ostreiculteur", keywords: ["ostreiculteur", "huitre", "parc", "mer"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-trufficulteur", label: "Devenir trufficulteur", keywords: ["trufficulteur", "truffe", "chene", "champignon"], oddsDenominator: 1000, category: "metier", estimate: true },
  { id: "px1-herboriste", label: "Devenir herboriste", keywords: ["herboriste", "plante", "tisane", "medicinal"], oddsDenominator: 500, category: "metier", estimate: true },
  { id: "px1-naturopathe", label: "Devenir naturopathe", keywords: ["naturopathe", "nature", "sante", "cabinet"], oddsDenominator: 300, category: "metier", estimate: true },
  { id: "px1-podologue", label: "Devenir pedicure-podologue", keywords: ["podologue", "pied", "semelle", "cabinet"], oddsDenominator: 120, category: "metier", estimate: true },
  { id: "px1-orthophoniste", label: "Devenir orthophoniste", keywords: ["orthophoniste", "parole", "langage", "cabinet"], oddsDenominator: 100, category: "metier", estimate: true },
  { id: "px1-audioprothesiste", label: "Devenir audioprothesiste", keywords: ["audioprothesiste", "audition", "appareil", "oreille"], oddsDenominator: 150, category: "metier", estimate: true },
  { id: "px1-opticien", label: "Devenir opticien", keywords: ["opticien", "lunette", "vue", "magasin"], oddsDenominator: 130, category: "metier", estimate: true },
  { id: "px1-opticien-franchise", label: "Ouvrir un magasin d'optique en franchise", keywords: ["opticien", "franchise", "magasin", "lunette"], oddsDenominator: 250, category: "entrepreneuriat", estimate: true },
  { id: "px1-prothesiste-dentaire", label: "Devenir prothesiste dentaire", keywords: ["prothesiste", "dentaire", "dent", "laboratoire"], oddsDenominator: 200, category: "metier", estimate: true },
  { id: "px1-dieteticien", label: "Devenir dieteticien", keywords: ["dieteticien", "nutrition", "regime", "cabinet"], oddsDenominator: 180, category: "metier", estimate: true },
  { id: "px1-psychomotricien", label: "Devenir psychomotricien", keywords: ["psychomotricien", "motricite", "enfant", "reeducation"], oddsDenominator: 150, category: "metier", estimate: true },
  { id: "px1-ergotherapeute", label: "Devenir ergotherapeute", keywords: ["ergotherapeute", "autonomie", "reeducation", "soin"], oddsDenominator: 150, category: "metier", estimate: true },
  { id: "px1-art-therapeute", label: "Devenir art-therapeute", keywords: ["art", "therapeute", "creation", "soin"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-hypnotherapeute", label: "Devenir hypnotherapeute", keywords: ["hypnotherapeute", "hypnose", "therapie", "cabinet"], oddsDenominator: 350, category: "metier", estimate: true },
  { id: "px1-conseiller-funeraire", label: "Devenir conseiller funeraire", keywords: ["conseiller", "funeraire", "pompes", "deuil"], oddsDenominator: 200, category: "metier", estimate: true },
  { id: "px1-genealogiste", label: "Devenir genealogiste successoral", keywords: ["genealogiste", "succession", "famille", "recherche"], oddsDenominator: 600, category: "metier", estimate: true },
  { id: "px1-expert-automobile", label: "Devenir expert automobile", keywords: ["expert", "automobile", "voiture", "sinistre"], oddsDenominator: 300, category: "metier", estimate: true },
  { id: "px1-geometre", label: "Devenir geometre-expert", keywords: ["geometre", "expert", "terrain", "mesure"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-hydrogeologue", label: "Devenir hydrogeologue", keywords: ["hydrogeologue", "eau", "nappe", "sol"], oddsDenominator: 700, category: "metier", estimate: true },
  { id: "px1-oenologue", label: "Devenir oenologue", keywords: ["oenologue", "vin", "degustation", "cave"], oddsDenominator: 600, category: "metier", estimate: true },
  { id: "px1-sommelier", label: "Devenir sommelier en restaurant etoile", keywords: ["sommelier", "vin", "restaurant", "etoile"], oddsDenominator: 800, category: "metier", estimate: true },
  { id: "px1-barista", label: "Devenir barista specialise", keywords: ["barista", "cafe", "expresso", "torrefaction"], oddsDenominator: 250, category: "metier", estimate: true },
  { id: "px1-glacier", label: "Devenir glacier artisan", keywords: ["glacier", "glace", "sorbet", "artisan"], oddsDenominator: 300, category: "metier", estimate: true },
  { id: "px1-traiteur", label: "Devenir traiteur", keywords: ["traiteur", "reception", "cuisine", "buffet"], oddsDenominator: 250, category: "entrepreneuriat", estimate: true },
  { id: "px1-caviste", label: "Devenir caviste", keywords: ["caviste", "vin", "cave", "boutique"], oddsDenominator: 300, category: "metier", estimate: true },
  { id: "px1-primeur", label: "Devenir primeur", keywords: ["primeur", "fruit", "legume", "marche"], oddsDenominator: 200, category: "metier", estimate: true },
  { id: "px1-poissonnier", label: "Devenir poissonnier", keywords: ["poissonnier", "poisson", "etal", "mer"], oddsDenominator: 250, category: "metier", estimate: true },
  { id: "px1-boucher-charcutier", label: "Devenir boucher-charcutier", keywords: ["boucher", "charcutier", "viande", "boutique"], oddsDenominator: 200, category: "metier", estimate: true },
  { id: "px1-boulanger-village", label: "Devenir boulanger d'un village", keywords: ["boulanger", "pain", "village", "fournil"], oddsDenominator: 180, category: "metier", estimate: true },
  { id: "px1-meunier", label: "Devenir meunier", keywords: ["meunier", "moulin", "farine", "ble"], oddsDenominator: 600, category: "metier", estimate: true },
  { id: "px1-chocolatier-bean-to-bar", label: "Devenir chocolatier bean to bar", keywords: ["chocolatier", "cacao", "feve", "tablette"], oddsDenominator: 500, category: "metier", estimate: true },
  { id: "px1-confiseur", label: "Devenir confiseur", keywords: ["confiseur", "bonbon", "sucre", "douceur"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-biscuitier", label: "Devenir biscuitier artisanal", keywords: ["biscuitier", "biscuit", "four", "gateau"], oddsDenominator: 450, category: "metier", estimate: true },
  { id: "px1-torrefacteur", label: "Devenir torrefacteur de cafe", keywords: ["torrefacteur", "cafe", "grain", "torrefaction"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-saliniere", label: "Devenir paludier recoltant de sel", keywords: ["paludier", "sel", "marais", "salant"], oddsDenominator: 700, category: "metier", estimate: true },
  { id: "px1-mytiliculteur", label: "Devenir mytiliculteur", keywords: ["mytiliculteur", "moule", "bouchot", "mer"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-conchyliculteur", label: "Devenir conchyliculteur", keywords: ["conchyliculteur", "coquillage", "elevage", "mer"], oddsDenominator: 450, category: "metier", estimate: true },
  { id: "px1-marin-pecheur", label: "Devenir marin-pecheur patron", keywords: ["marin", "pecheur", "bateau", "peche"], oddsDenominator: 500, category: "metier", estimate: true },
  { id: "px1-chevrier", label: "Devenir chevrier fromager", keywords: ["chevrier", "chevre", "fromage", "elevage"], oddsDenominator: 350, category: "metier", estimate: true },
  { id: "px1-berger-transhumant", label: "Devenir berger transhumant", keywords: ["berger", "transhumance", "mouton", "montagne"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-eleveur-volaille", label: "Devenir eleveur de volaille fermiere", keywords: ["eleveur", "volaille", "poulet", "ferme"], oddsDenominator: 300, category: "metier", estimate: true },
  { id: "px1-maraicher-bio", label: "Devenir maraicher bio", keywords: ["maraicher", "bio", "legume", "potager"], oddsDenominator: 250, category: "metier", estimate: true },
  { id: "px1-arboriculteur", label: "Devenir arboriculteur fruitier", keywords: ["arboriculteur", "fruit", "verger", "arbre"], oddsDenominator: 350, category: "metier", estimate: true },
  { id: "px1-horticulteur", label: "Devenir horticulteur", keywords: ["horticulteur", "fleur", "serre", "plante"], oddsDenominator: 300, category: "metier", estimate: true },
  { id: "px1-pepinieriste", label: "Devenir pepinieriste", keywords: ["pepinieriste", "plante", "arbre", "pepiniere"], oddsDenominator: 350, category: "metier", estimate: true },
  { id: "px1-paysagiste", label: "Devenir paysagiste concepteur", keywords: ["paysagiste", "jardin", "espace", "vert"], oddsDenominator: 300, category: "metier", estimate: true },
  { id: "px1-jardinier-prive", label: "Devenir jardinier de proprietes privees", keywords: ["jardinier", "propriete", "parc", "entretien"], oddsDenominator: 200, category: "metier", estimate: true },
  { id: "px1-fleuriste", label: "Devenir fleuriste", keywords: ["fleuriste", "fleur", "bouquet", "boutique"], oddsDenominator: 250, category: "metier", estimate: true },
  { id: "px1-fleuriste-evenementiel", label: "Devenir fleuriste evenementiel", keywords: ["fleuriste", "evenementiel", "mariage", "decoration"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-lavandiculteur", label: "Devenir producteur de lavande", keywords: ["lavande", "huile", "champ", "provence"], oddsDenominator: 600, category: "metier", estimate: true },
  { id: "px1-safranier", label: "Devenir safranier", keywords: ["safranier", "safran", "crocus", "epice"], oddsDenominator: 800, category: "metier", estimate: true },
  { id: "px1-distillateur", label: "Devenir distillateur d'huiles essentielles", keywords: ["distillateur", "huile", "essentielle", "alambic"], oddsDenominator: 700, category: "metier", estimate: true },
  { id: "px1-bouilleur-cru", label: "Devenir bouilleur de cru", keywords: ["bouilleur", "cru", "eau-de-vie", "alambic"], oddsDenominator: 900, category: "metier", estimate: true },
  { id: "px1-cidrier", label: "Devenir producteur de cidre", keywords: ["cidre", "pomme", "cidrerie", "verger"], oddsDenominator: 500, category: "metier", estimate: true },
  { id: "px1-tonnelier", label: "Devenir tonnelier", keywords: ["tonnelier", "tonneau", "fut", "bois"], oddsDenominator: 800, category: "metier", estimate: true },
  { id: "px1-vannier", label: "Devenir vannier", keywords: ["vannier", "osier", "panier", "tressage"], oddsDenominator: 600, category: "metier", estimate: true },
  { id: "px1-forgeron", label: "Devenir forgeron d'art", keywords: ["forgeron", "fer", "forge", "metal"], oddsDenominator: 500, category: "metier", estimate: true },
  { id: "px1-coutelier", label: "Devenir coutelier", keywords: ["coutelier", "couteau", "lame", "forge"], oddsDenominator: 700, category: "metier", estimate: true },
  { id: "px1-armurier", label: "Devenir armurier", keywords: ["armurier", "arme", "fusil", "atelier"], oddsDenominator: 800, category: "metier", estimate: true },
  { id: "px1-fondeur-bronze", label: "Devenir fondeur de bronze d'art", keywords: ["fondeur", "bronze", "sculpture", "fonderie"], oddsDenominator: 1000, category: "metier", estimate: true },
  { id: "px1-doreur", label: "Devenir doreur sur bois", keywords: ["doreur", "or", "feuille", "bois"], oddsDenominator: 800, category: "metier", estimate: true },
  { id: "px1-vitrailliste", label: "Devenir maitre-verrier vitrailliste", keywords: ["vitrailliste", "vitrail", "verre", "plomb"], oddsDenominator: 900, category: "metier", estimate: true },
  { id: "px1-mosaiste", label: "Devenir mosaiste", keywords: ["mosaiste", "mosaique", "tesselle", "art"], oddsDenominator: 800, category: "artiste", estimate: true },
  { id: "px1-staffeur", label: "Devenir staffeur ornemaniste", keywords: ["staffeur", "platre", "moulure", "ornement"], oddsDenominator: 700, category: "metier", estimate: true },
  { id: "px1-stucateur", label: "Devenir stucateur", keywords: ["stucateur", "stuc", "enduit", "decor"], oddsDenominator: 700, category: "metier", estimate: true },
  { id: "px1-peintre-decorateur", label: "Devenir peintre en decor", keywords: ["peintre", "decor", "trompe-oeil", "patine"], oddsDenominator: 500, category: "metier", estimate: true },
  { id: "px1-restaurateur-monuments", label: "Devenir restaurateur de monuments historiques", keywords: ["restaurateur", "monument", "patrimoine", "pierre"], oddsDenominator: 800, category: "metier", estimate: true },
  { id: "px1-archeologue", label: "Devenir archeologue de terrain", keywords: ["archeologue", "fouille", "vestige", "terrain"], oddsDenominator: 1200, category: "metier", estimate: true },
  { id: "px1-relieur", label: "Devenir relieur d'art", keywords: ["relieur", "livre", "reliure", "cuir"], oddsDenominator: 700, category: "metier", estimate: true },
  { id: "px1-calligraphe", label: "Devenir calligraphe", keywords: ["calligraphe", "ecriture", "plume", "encre"], oddsDenominator: 900, category: "artiste", estimate: true },
  { id: "px1-enlumineur", label: "Devenir enlumineur", keywords: ["enlumineur", "enluminure", "manuscrit", "or"], oddsDenominator: 1500, category: "artiste", estimate: true },
  { id: "px1-graveur", label: "Devenir graveur sur metaux", keywords: ["graveur", "gravure", "metal", "burin"], oddsDenominator: 800, category: "metier", estimate: true },
  { id: "px1-medailleur", label: "Devenir medailleur", keywords: ["medailleur", "medaille", "gravure", "monnaie"], oddsDenominator: 1200, category: "metier", estimate: true },
  { id: "px1-tourneur-bois", label: "Devenir tourneur sur bois", keywords: ["tourneur", "bois", "tour", "objet"], oddsDenominator: 500, category: "metier", estimate: true },
  { id: "px1-marqueteur", label: "Devenir marqueteur", keywords: ["marqueteur", "marqueterie", "bois", "placage"], oddsDenominator: 800, category: "metier", estimate: true },
  { id: "px1-restaurateur-meubles", label: "Devenir restaurateur de meubles anciens", keywords: ["restaurateur", "meuble", "ancien", "bois"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-tapissier-decorateur", label: "Devenir tapissier-decorateur", keywords: ["tapissier", "decorateur", "rideau", "tissu"], oddsDenominator: 350, category: "metier", estimate: true },
  { id: "px1-couturier", label: "Devenir couturier sur mesure", keywords: ["couturier", "couture", "mesure", "atelier"], oddsDenominator: 500, category: "metier", estimate: true },
  { id: "px1-modeliste", label: "Devenir modeliste", keywords: ["modeliste", "patron", "mode", "vetement"], oddsDenominator: 600, category: "metier", estimate: true },
  { id: "px1-styliste-mode", label: "Devenir styliste de mode", keywords: ["styliste", "mode", "collection", "creation"], oddsDenominator: 1500, category: "artiste", estimate: true },
  { id: "px1-chapelier", label: "Devenir chapelier modiste", keywords: ["chapelier", "modiste", "chapeau", "feutre"], oddsDenominator: 900, category: "metier", estimate: true },
  { id: "px1-bottier", label: "Devenir bottier sur mesure", keywords: ["bottier", "chaussure", "mesure", "cuir"], oddsDenominator: 1000, category: "metier", estimate: true },
  { id: "px1-gantier", label: "Devenir gantier", keywords: ["gantier", "gant", "cuir", "couture"], oddsDenominator: 1000, category: "metier", estimate: true },
  { id: "px1-plumassier", label: "Devenir plumassier", keywords: ["plumassier", "plume", "ornement", "mode"], oddsDenominator: 1500, category: "metier", estimate: true },
  { id: "px1-brodeur", label: "Devenir brodeur d'art", keywords: ["brodeur", "broderie", "fil", "or"], oddsDenominator: 900, category: "metier", estimate: true },
  { id: "px1-dentelliere", label: "Devenir dentellier", keywords: ["dentellier", "dentelle", "fil", "fuseau"], oddsDenominator: 1200, category: "metier", estimate: true },
  { id: "px1-tisserand", label: "Devenir tisserand", keywords: ["tisserand", "tissage", "metier", "laine"], oddsDenominator: 700, category: "metier", estimate: true },
  { id: "px1-feutrier", label: "Devenir feutrier", keywords: ["feutrier", "feutre", "laine", "textile"], oddsDenominator: 900, category: "metier", estimate: true },
  { id: "px1-sellier", label: "Devenir sellier-harnacheur", keywords: ["sellier", "selle", "cuir", "cheval"], oddsDenominator: 700, category: "metier", estimate: true },
  { id: "px1-bourrelier", label: "Devenir bourrelier", keywords: ["bourrelier", "cuir", "harnais", "sellerie"], oddsDenominator: 800, category: "metier", estimate: true },
  { id: "px1-veterinaire-rural", label: "Devenir veterinaire rural", keywords: ["veterinaire", "rural", "ferme", "betail"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-veterinaire-canin", label: "Ouvrir une clinique veterinaire canine", keywords: ["veterinaire", "clinique", "chien", "chat"], oddsDenominator: 350, category: "metier", estimate: true },
  { id: "px1-veterinaire-equin", label: "Devenir veterinaire equin", keywords: ["veterinaire", "equin", "cheval", "haras"], oddsDenominator: 600, category: "metier", estimate: true },
  { id: "px1-veterinaire-nac", label: "Devenir veterinaire pour nouveaux animaux", keywords: ["veterinaire", "nac", "reptile", "exotique"], oddsDenominator: 700, category: "metier", estimate: true },
  { id: "px1-toiletteur", label: "Devenir toiletteur canin", keywords: ["toiletteur", "chien", "salon", "animal"], oddsDenominator: 200, category: "metier", estimate: true },
  { id: "px1-educateur-canin", label: "Devenir educateur canin", keywords: ["educateur", "canin", "chien", "dressage"], oddsDenominator: 250, category: "metier", estimate: true },
  { id: "px1-comportementaliste-animal", label: "Devenir comportementaliste animalier", keywords: ["comportementaliste", "animal", "chien", "chat"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-pet-sitter", label: "Devenir pet-sitter professionnel", keywords: ["pet", "sitter", "garde", "animal"], oddsDenominator: 300, category: "entrepreneuriat", estimate: true },
  { id: "px1-soigneur-zoo", label: "Devenir soigneur animalier en zoo", keywords: ["soigneur", "animalier", "zoo", "animal"], oddsDenominator: 800, category: "metier", estimate: true },
  { id: "px1-garde-chasse", label: "Devenir garde-chasse", keywords: ["garde", "chasse", "gibier", "foret"], oddsDenominator: 500, category: "metier", estimate: true },
  { id: "px1-garde-peche", label: "Devenir garde-peche", keywords: ["garde", "peche", "riviere", "surveillance"], oddsDenominator: 500, category: "metier", estimate: true },
  { id: "px1-garde-forestier", label: "Devenir garde forestier", keywords: ["garde", "forestier", "foret", "nature"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-bucheron", label: "Devenir bucheron", keywords: ["bucheron", "bois", "arbre", "foret"], oddsDenominator: 250, category: "metier", estimate: true },
  { id: "px1-debardeur-cheval", label: "Devenir debardeur a cheval", keywords: ["debardeur", "cheval", "bois", "foret"], oddsDenominator: 1000, category: "metier", estimate: true },
  { id: "px1-charbonnier", label: "Devenir charbonnier", keywords: ["charbonnier", "charbon", "bois", "meule"], oddsDenominator: 1500, category: "metier", estimate: true },
  { id: "px1-cueilleur-plantes", label: "Devenir cueilleur de plantes sauvages", keywords: ["cueilleur", "plante", "sauvage", "montagne"], oddsDenominator: 800, category: "metier", estimate: true },
  { id: "px1-guide-montagne", label: "Devenir guide de haute montagne", keywords: ["guide", "montagne", "alpinisme", "sommet"], oddsDenominator: 700, category: "metier", estimate: true },
  { id: "px1-moniteur-ski", label: "Devenir moniteur de ski", keywords: ["moniteur", "ski", "piste", "neige"], oddsDenominator: 300, category: "metier", estimate: true },
  { id: "px1-pisteur-secouriste", label: "Devenir pisteur-secouriste", keywords: ["pisteur", "secouriste", "ski", "montagne"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-accompagnateur-rando", label: "Devenir accompagnateur en montagne", keywords: ["accompagnateur", "randonnee", "montagne", "sentier"], oddsDenominator: 300, category: "metier", estimate: true },
  { id: "px1-moniteur-plongee", label: "Devenir moniteur de plongee", keywords: ["moniteur", "plongee", "mer", "scaphandre"], oddsDenominator: 350, category: "metier", estimate: true },
  { id: "px1-moniteur-voile", label: "Devenir moniteur de voile", keywords: ["moniteur", "voile", "bateau", "mer"], oddsDenominator: 350, category: "metier", estimate: true },
  { id: "px1-skipper", label: "Devenir skipper professionnel", keywords: ["skipper", "voilier", "mer", "navigation"], oddsDenominator: 600, category: "metier", estimate: true },
  { id: "px1-pilote-ligne", label: "Devenir pilote de ligne", keywords: ["pilote", "ligne", "avion", "aviation"], oddsDenominator: 800, category: "metier", estimate: true },
  { id: "px1-pilote-helicoptere", label: "Devenir pilote d'helicoptere", keywords: ["pilote", "helicoptere", "vol", "aviation"], oddsDenominator: 1000, category: "metier", estimate: true },
  { id: "px1-controleur-aerien", label: "Devenir controleur aerien", keywords: ["controleur", "aerien", "tour", "avion"], oddsDenominator: 700, category: "metier", estimate: true },
  { id: "px1-mecanicien-aero", label: "Devenir mecanicien aeronautique", keywords: ["mecanicien", "aeronautique", "avion", "maintenance"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-conducteur-train", label: "Devenir conducteur de train", keywords: ["conducteur", "train", "rail", "sncf"], oddsDenominator: 250, category: "metier", estimate: true },
  { id: "px1-chauffeur-routier", label: "Devenir chauffeur routier", keywords: ["chauffeur", "routier", "camion", "transport"], oddsDenominator: 100, category: "metier", estimate: true },
  { id: "px1-grutier", label: "Devenir grutier", keywords: ["grutier", "grue", "chantier", "levage"], oddsDenominator: 200, category: "metier", estimate: true },
  { id: "px1-conducteur-engins", label: "Devenir conducteur d'engins", keywords: ["conducteur", "engins", "pelle", "chantier"], oddsDenominator: 150, category: "metier", estimate: true },
  { id: "px1-macon", label: "Devenir maitre macon", keywords: ["macon", "construction", "mur", "chantier"], oddsDenominator: 120, category: "metier", estimate: true },
  { id: "px1-charpentier-bois", label: "Devenir charpentier bois", keywords: ["charpentier", "bois", "toit", "poutre"], oddsDenominator: 150, category: "metier", estimate: true },
  { id: "px1-menuisier", label: "Devenir menuisier", keywords: ["menuisier", "bois", "fenetre", "porte"], oddsDenominator: 150, category: "metier", estimate: true },
  { id: "px1-plaquiste", label: "Devenir plaquiste", keywords: ["plaquiste", "placo", "cloison", "chantier"], oddsDenominator: 120, category: "metier", estimate: true },
  { id: "px1-carreleur", label: "Devenir carreleur", keywords: ["carreleur", "carrelage", "faience", "sol"], oddsDenominator: 130, category: "metier", estimate: true },
  { id: "px1-plombier-chauffagiste", label: "Devenir plombier-chauffagiste", keywords: ["plombier", "chauffagiste", "eau", "chaudiere"], oddsDenominator: 110, category: "metier", estimate: true },
  { id: "px1-electricien", label: "Devenir electricien du batiment", keywords: ["electricien", "batiment", "cable", "installation"], oddsDenominator: 110, category: "metier", estimate: true },
  { id: "px1-peintre-batiment", label: "Devenir peintre en batiment", keywords: ["peintre", "batiment", "mur", "chantier"], oddsDenominator: 120, category: "metier", estimate: true },
  { id: "px1-serrurier", label: "Devenir serrurier-metallier", keywords: ["serrurier", "metallier", "serrure", "metal"], oddsDenominator: 150, category: "metier", estimate: true },
  { id: "px1-vitrier", label: "Devenir vitrier", keywords: ["vitrier", "vitre", "verre", "fenetre"], oddsDenominator: 180, category: "metier", estimate: true },
  { id: "px1-frigoriste", label: "Devenir frigoriste", keywords: ["frigoriste", "froid", "climatisation", "installation"], oddsDenominator: 200, category: "metier", estimate: true },
  { id: "px1-domoticien", label: "Devenir domoticien", keywords: ["domoticien", "domotique", "maison", "connecte"], oddsDenominator: 250, category: "metier", estimate: true },
  { id: "px1-installateur-solaire", label: "Devenir installateur de panneaux solaires", keywords: ["installateur", "solaire", "panneau", "energie"], oddsDenominator: 200, category: "metier", estimate: true },
  { id: "px1-ramoneur", label: "Devenir ramoneur", keywords: ["ramoneur", "cheminee", "suie", "conduit"], oddsDenominator: 250, category: "metier", estimate: true },
  { id: "px1-fumiste", label: "Devenir fumiste", keywords: ["fumiste", "cheminee", "poele", "foyer"], oddsDenominator: 300, category: "metier", estimate: true },
  { id: "px1-paveur", label: "Devenir paveur", keywords: ["paveur", "pave", "voirie", "sol"], oddsDenominator: 250, category: "metier", estimate: true },
  { id: "px1-etancheur", label: "Devenir etancheur", keywords: ["etancheur", "toit", "etancheite", "terrasse"], oddsDenominator: 200, category: "metier", estimate: true },
  { id: "px1-puisatier", label: "Devenir puisatier", keywords: ["puisatier", "puits", "eau", "forage"], oddsDenominator: 500, category: "metier", estimate: true },
  { id: "px1-foreur", label: "Devenir foreur", keywords: ["foreur", "forage", "sol", "sondage"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-kinesitherapeute", label: "Devenir kinesitherapeute liberal", keywords: ["kinesitherapeute", "kine", "reeducation", "cabinet"], oddsDenominator: 120, category: "metier", estimate: true },
  { id: "px1-infirmier-liberal", label: "Devenir infirmier liberal", keywords: ["infirmier", "liberal", "soin", "domicile"], oddsDenominator: 80, category: "metier", estimate: true },
  { id: "px1-medecin-generaliste", label: "Devenir medecin generaliste", keywords: ["medecin", "generaliste", "cabinet", "patient"], oddsDenominator: 300, category: "metier", estimate: true },
  { id: "px1-medecin-campagne", label: "Devenir medecin de campagne", keywords: ["medecin", "campagne", "rural", "village"], oddsDenominator: 250, category: "metier", estimate: true },
  { id: "px1-cardiologue", label: "Devenir cardiologue", keywords: ["cardiologue", "coeur", "specialiste", "cabinet"], oddsDenominator: 1200, category: "metier", estimate: true },
  { id: "px1-dermatologue", label: "Devenir dermatologue", keywords: ["dermatologue", "peau", "specialiste", "cabinet"], oddsDenominator: 1300, category: "metier", estimate: true },
  { id: "px1-ophtalmologue", label: "Devenir ophtalmologue", keywords: ["ophtalmologue", "oeil", "vue", "specialiste"], oddsDenominator: 1400, category: "metier", estimate: true },
  { id: "px1-radiologue", label: "Devenir radiologue", keywords: ["radiologue", "radio", "imagerie", "specialiste"], oddsDenominator: 1500, category: "metier", estimate: true },
  { id: "px1-anesthesiste", label: "Devenir anesthesiste-reanimateur", keywords: ["anesthesiste", "anesthesie", "bloc", "reanimation"], oddsDenominator: 1400, category: "metier", estimate: true },
  { id: "px1-chirurgien-orthopediste", label: "Devenir chirurgien orthopediste", keywords: ["chirurgien", "orthopediste", "os", "bloc"], oddsDenominator: 1800, category: "metier", estimate: true },
  { id: "px1-neurochirurgien", label: "Devenir neurochirurgien", keywords: ["neurochirurgien", "cerveau", "bloc", "specialiste"], oddsDenominator: 3000, category: "metier", estimate: true },
  { id: "px1-psychiatre", label: "Devenir psychiatre", keywords: ["psychiatre", "psyche", "cabinet", "mental"], oddsDenominator: 900, category: "metier", estimate: true },
  { id: "px1-psychologue", label: "Devenir psychologue clinicien", keywords: ["psychologue", "clinicien", "cabinet", "therapie"], oddsDenominator: 250, category: "metier", estimate: true },
  { id: "px1-psychanalyste", label: "Devenir psychanalyste", keywords: ["psychanalyste", "analyse", "cabinet", "divan"], oddsDenominator: 500, category: "metier", estimate: true },
  { id: "px1-pharmacien-officine", label: "Devenir pharmacien titulaire d'officine", keywords: ["pharmacien", "officine", "pharmacie", "medicament"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-preparateur-pharmacie", label: "Devenir preparateur en pharmacie", keywords: ["preparateur", "pharmacie", "medicament", "officine"], oddsDenominator: 150, category: "metier", estimate: true },
  { id: "px1-chirurgien-dentiste", label: "Devenir chirurgien-dentiste", keywords: ["chirurgien", "dentiste", "dent", "cabinet"], oddsDenominator: 500, category: "metier", estimate: true },
  { id: "px1-orthodontiste", label: "Devenir orthodontiste", keywords: ["orthodontiste", "dent", "appareil", "cabinet"], oddsDenominator: 900, category: "metier", estimate: true },
  { id: "px1-orthoptiste", label: "Devenir orthoptiste", keywords: ["orthoptiste", "oeil", "reeducation", "vue"], oddsDenominator: 200, category: "metier", estimate: true },
  { id: "px1-manipulateur-radio", label: "Devenir manipulateur radio", keywords: ["manipulateur", "radio", "imagerie", "hopital"], oddsDenominator: 180, category: "metier", estimate: true },
  { id: "px1-aide-soignant", label: "Devenir aide-soignant", keywords: ["aide", "soignant", "hopital", "soin"], oddsDenominator: 60, category: "metier", estimate: true },
  { id: "px1-ambulancier", label: "Devenir ambulancier", keywords: ["ambulancier", "ambulance", "urgence", "transport"], oddsDenominator: 100, category: "metier", estimate: true },
  { id: "px1-opticien-lunetier", label: "Devenir opticien-lunetier independant", keywords: ["opticien", "lunetier", "lunette", "independant"], oddsDenominator: 300, category: "entrepreneuriat", estimate: true },
  { id: "px1-acupuncteur", label: "Devenir acupuncteur", keywords: ["acupuncteur", "aiguille", "energie", "cabinet"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-reflexologue", label: "Devenir reflexologue", keywords: ["reflexologue", "pied", "massage", "cabinet"], oddsDenominator: 350, category: "metier", estimate: true },
  { id: "px1-etiopathe", label: "Devenir etiopathe", keywords: ["etiopathe", "manipulation", "cause", "cabinet"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-chiropracteur", label: "Devenir chiropracteur", keywords: ["chiropracteur", "vertebre", "manipulation", "cabinet"], oddsDenominator: 350, category: "metier", estimate: true },
  { id: "px1-masseur-bien-etre", label: "Devenir masseur bien-etre", keywords: ["masseur", "massage", "detente", "spa"], oddsDenominator: 250, category: "metier", estimate: true },
  { id: "px1-estheticienne", label: "Devenir estheticienne", keywords: ["estheticienne", "soin", "visage", "institut"], oddsDenominator: 200, category: "metier", estimate: true },
  { id: "px1-prothesiste-ongulaire", label: "Devenir prothesiste ongulaire", keywords: ["prothesiste", "ongle", "manucure", "nail"], oddsDenominator: 250, category: "metier", estimate: true },
  { id: "px1-coiffeur", label: "Devenir coiffeur a son compte", keywords: ["coiffeur", "salon", "cheveux", "coupe"], oddsDenominator: 200, category: "metier", estimate: true },
  { id: "px1-coiffeur-visagiste", label: "Devenir coiffeur visagiste", keywords: ["coiffeur", "visagiste", "cheveux", "salon"], oddsDenominator: 350, category: "metier", estimate: true },
  { id: "px1-barbier", label: "Devenir barbier", keywords: ["barbier", "barbe", "rasage", "salon"], oddsDenominator: 250, category: "metier", estimate: true },
  { id: "px1-maquilleur-pro", label: "Devenir maquilleur professionnel", keywords: ["maquilleur", "maquillage", "beaute", "mode"], oddsDenominator: 500, category: "metier", estimate: true },
  { id: "px1-tatoueur", label: "Devenir tatoueur", keywords: ["tatoueur", "tatouage", "encre", "salon"], oddsDenominator: 400, category: "artiste", estimate: true },
  { id: "px1-perceur", label: "Devenir perceur professionnel", keywords: ["perceur", "piercing", "bijou", "salon"], oddsDenominator: 450, category: "metier", estimate: true },
  { id: "px1-spa-praticien", label: "Devenir praticien spa", keywords: ["spa", "praticien", "soin", "bien-etre"], oddsDenominator: 250, category: "metier", estimate: true },
  { id: "px1-coach-sportif", label: "Devenir coach sportif", keywords: ["coach", "sportif", "fitness", "entrainement"], oddsDenominator: 300, category: "metier", estimate: true },
  { id: "px1-prof-yoga", label: "Devenir professeur de yoga", keywords: ["yoga", "professeur", "posture", "studio"], oddsDenominator: 350, category: "metier", estimate: true },
  { id: "px1-prof-pilates", label: "Devenir professeur de pilates", keywords: ["pilates", "professeur", "gainage", "studio"], oddsDenominator: 350, category: "metier", estimate: true },
  { id: "px1-avocat-affaires", label: "Devenir avocat d'affaires", keywords: ["avocat", "affaires", "droit", "cabinet"], oddsDenominator: 1500, category: "metier", estimate: true },
  { id: "px1-avocat-penaliste", label: "Devenir avocat penaliste", keywords: ["avocat", "penaliste", "tribunal", "defense"], oddsDenominator: 1200, category: "metier", estimate: true },
  { id: "px1-avocat-divorce", label: "Devenir avocat en droit de la famille", keywords: ["avocat", "famille", "divorce", "cabinet"], oddsDenominator: 600, category: "metier", estimate: true },
  { id: "px1-huissier", label: "Devenir commissaire de justice", keywords: ["huissier", "commissaire", "justice", "constat"], oddsDenominator: 900, category: "metier", estimate: true },
  { id: "px1-magistrat", label: "Devenir magistrat", keywords: ["magistrat", "juge", "tribunal", "justice"], oddsDenominator: 1500, category: "metier", estimate: true },
  { id: "px1-expert-comptable", label: "Devenir expert-comptable", keywords: ["expert", "comptable", "bilan", "cabinet"], oddsDenominator: 700, category: "metier", estimate: true },
  { id: "px1-commissaire-comptes", label: "Devenir commissaire aux comptes", keywords: ["commissaire", "comptes", "audit", "controle"], oddsDenominator: 900, category: "metier", estimate: true },
  { id: "px1-conseiller-gestion-patrimoine", label: "Devenir conseiller en gestion de patrimoine", keywords: ["conseiller", "patrimoine", "gestion", "finance"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-courtier-assurance", label: "Devenir courtier en assurances", keywords: ["courtier", "assurance", "contrat", "client"], oddsDenominator: 300, category: "entrepreneuriat", estimate: true },
  { id: "px1-courtier-credit", label: "Devenir courtier en credit immobilier", keywords: ["courtier", "credit", "pret", "immobilier"], oddsDenominator: 350, category: "entrepreneuriat", estimate: true },
  { id: "px1-agent-immobilier", label: "Devenir agent immobilier", keywords: ["agent", "immobilier", "vente", "agence"], oddsDenominator: 250, category: "metier", estimate: true },
  { id: "px1-agent-immobilier-luxe", label: "Devenir agent immobilier de luxe", keywords: ["agent", "immobilier", "luxe", "prestige"], oddsDenominator: 1200, category: "metier", estimate: true },
  { id: "px1-mandataire-immo", label: "Devenir mandataire immobilier independant", keywords: ["mandataire", "immobilier", "independant", "vente"], oddsDenominator: 300, category: "entrepreneuriat", estimate: true },
  { id: "px1-syndic", label: "Devenir syndic de copropriete", keywords: ["syndic", "copropriete", "immeuble", "gestion"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-administrateur-biens", label: "Devenir administrateur de biens", keywords: ["administrateur", "biens", "location", "gestion"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-diagnostiqueur-immo", label: "Devenir diagnostiqueur immobilier", keywords: ["diagnostiqueur", "immobilier", "dpe", "controle"], oddsDenominator: 250, category: "metier", estimate: true },
  { id: "px1-architecte", label: "Devenir architecte", keywords: ["architecte", "plan", "batiment", "agence"], oddsDenominator: 600, category: "metier", estimate: true },
  { id: "px1-architecte-interieur", label: "Devenir architecte d'interieur", keywords: ["architecte", "interieur", "decoration", "amenagement"], oddsDenominator: 500, category: "metier", estimate: true },
  { id: "px1-decorateur-interieur", label: "Devenir decorateur d'interieur", keywords: ["decorateur", "interieur", "deco", "amenagement"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-urbaniste", label: "Devenir urbaniste", keywords: ["urbaniste", "ville", "amenagement", "territoire"], oddsDenominator: 600, category: "metier", estimate: true },
  { id: "px1-ingenieur-structure", label: "Devenir ingenieur structure", keywords: ["ingenieur", "structure", "calcul", "batiment"], oddsDenominator: 500, category: "metier", estimate: true },
  { id: "px1-ingenieur-aerospatial", label: "Devenir ingenieur aerospatial", keywords: ["ingenieur", "aerospatial", "fusee", "satellite"], oddsDenominator: 800, category: "metier", estimate: true },
  { id: "px1-ingenieur-nucleaire", label: "Devenir ingenieur nucleaire", keywords: ["ingenieur", "nucleaire", "centrale", "energie"], oddsDenominator: 900, category: "metier", estimate: true },
  { id: "px1-ingenieur-bioinfo", label: "Devenir ingenieur bio-informaticien", keywords: ["ingenieur", "bioinformatique", "genome", "donnees"], oddsDenominator: 700, category: "metier", estimate: true },
  { id: "px1-data-scientist", label: "Devenir data scientist", keywords: ["data", "scientist", "donnees", "modele"], oddsDenominator: 350, category: "metier", estimate: true },
  { id: "px1-developpeur-web", label: "Devenir developpeur web", keywords: ["developpeur", "web", "code", "site"], oddsDenominator: 150, category: "metier", estimate: true },
  { id: "px1-developpeur-mobile", label: "Devenir developpeur mobile", keywords: ["developpeur", "mobile", "application", "code"], oddsDenominator: 200, category: "metier", estimate: true },
  { id: "px1-developpeur-jeux", label: "Devenir developpeur de jeux video", keywords: ["developpeur", "jeu", "video", "code"], oddsDenominator: 500, category: "metier", estimate: true },
  { id: "px1-expert-cyber", label: "Devenir expert en cybersecurite", keywords: ["expert", "cybersecurite", "securite", "informatique"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-administrateur-systemes", label: "Devenir administrateur systemes et reseaux", keywords: ["administrateur", "systeme", "reseau", "serveur"], oddsDenominator: 250, category: "metier", estimate: true },
  { id: "px1-ux-designer", label: "Devenir UX designer", keywords: ["ux", "designer", "interface", "ergonomie"], oddsDenominator: 300, category: "metier", estimate: true },
  { id: "px1-graphiste", label: "Devenir graphiste independant", keywords: ["graphiste", "design", "visuel", "creation"], oddsDenominator: 300, category: "artiste", estimate: true },
  { id: "px1-illustrateur", label: "Devenir illustrateur", keywords: ["illustrateur", "dessin", "illustration", "edition"], oddsDenominator: 700, category: "artiste", estimate: true },
  { id: "px1-motion-designer", label: "Devenir motion designer", keywords: ["motion", "designer", "animation", "video"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-monteur-video", label: "Devenir monteur video", keywords: ["monteur", "video", "montage", "film"], oddsDenominator: 350, category: "metier", estimate: true },
  { id: "px1-cadreur", label: "Devenir cadreur", keywords: ["cadreur", "camera", "tournage", "image"], oddsDenominator: 500, category: "metier", estimate: true },
  { id: "px1-ingenieur-son", label: "Devenir ingenieur du son", keywords: ["ingenieur", "son", "studio", "audio"], oddsDenominator: 600, category: "metier", estimate: true },
  { id: "px1-photographe-mariage", label: "Devenir photographe de mariage", keywords: ["photographe", "mariage", "reportage", "image"], oddsDenominator: 300, category: "metier", estimate: true },
  { id: "px1-photographe-mode", label: "Devenir photographe de mode", keywords: ["photographe", "mode", "studio", "image"], oddsDenominator: 900, category: "artiste", estimate: true },
  { id: "px1-photographe-animalier", label: "Devenir photographe animalier", keywords: ["photographe", "animalier", "nature", "faune"], oddsDenominator: 1000, category: "artiste", estimate: true },
  { id: "px1-peintre-artiste", label: "Devenir peintre artiste vivant de son art", keywords: ["peintre", "artiste", "toile", "galerie"], oddsDenominator: 2000, category: "artiste", estimate: true },
  { id: "px1-sculpteur", label: "Devenir sculpteur professionnel", keywords: ["sculpteur", "sculpture", "atelier", "art"], oddsDenominator: 1800, category: "artiste", estimate: true },
  { id: "px1-graveur-estampe", label: "Devenir graveur d'estampes", keywords: ["graveur", "estampe", "gravure", "tirage"], oddsDenominator: 1500, category: "artiste", estimate: true },
  { id: "px1-comedien", label: "Devenir comedien professionnel", keywords: ["comedien", "theatre", "scene", "acteur"], oddsDenominator: 2500, category: "artiste", estimate: true },
  { id: "px1-comedien-doublage", label: "Devenir comedien de doublage", keywords: ["comedien", "doublage", "voix", "studio"], oddsDenominator: 1500, category: "artiste", estimate: true },
  { id: "px1-danseur-classique", label: "Devenir danseur classique professionnel", keywords: ["danseur", "classique", "ballet", "scene"], oddsDenominator: 3000, category: "artiste", estimate: true },
  { id: "px1-chorégraphe", label: "Devenir choregraphe", keywords: ["choregraphe", "danse", "creation", "scene"], oddsDenominator: 2000, category: "artiste", estimate: true },
  { id: "px1-musicien-orchestre", label: "Devenir musicien d'orchestre", keywords: ["musicien", "orchestre", "instrument", "concert"], oddsDenominator: 1500, category: "artiste", estimate: true },
  { id: "px1-chef-orchestre", label: "Devenir chef d'orchestre", keywords: ["chef", "orchestre", "direction", "concert"], oddsDenominator: 5000, category: "artiste", estimate: true },
  { id: "px1-compositeur", label: "Devenir compositeur de musique", keywords: ["compositeur", "musique", "partition", "creation"], oddsDenominator: 3000, category: "artiste", estimate: true },
  { id: "px1-prof-musique", label: "Devenir professeur de musique", keywords: ["professeur", "musique", "conservatoire", "instrument"], oddsDenominator: 250, category: "metier", estimate: true },
  { id: "px1-accordeur-piano", label: "Devenir accordeur de pianos", keywords: ["accordeur", "piano", "accord", "instrument"], oddsDenominator: 700, category: "metier", estimate: true },
  { id: "px1-facteur-orgues", label: "Devenir facteur d'orgues", keywords: ["facteur", "orgue", "tuyau", "eglise"], oddsDenominator: 2000, category: "metier", estimate: true },
  { id: "px1-facteur-pianos", label: "Devenir facteur de pianos", keywords: ["facteur", "piano", "fabrication", "instrument"], oddsDenominator: 1800, category: "metier", estimate: true },
  { id: "px1-romancier", label: "Devenir romancier publie", keywords: ["romancier", "roman", "livre", "edition"], oddsDenominator: 3000, category: "artiste", estimate: true },
  { id: "px1-scenariste", label: "Devenir scenariste", keywords: ["scenariste", "scenario", "film", "serie"], oddsDenominator: 2000, category: "artiste", estimate: true },
  { id: "px1-traducteur-litteraire", label: "Devenir traducteur litteraire", keywords: ["traducteur", "litteraire", "livre", "langue"], oddsDenominator: 1500, category: "metier", estimate: true },
  { id: "px1-traducteur-technique", label: "Devenir traducteur technique", keywords: ["traducteur", "technique", "langue", "document"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-interprete", label: "Devenir interprete de conference", keywords: ["interprete", "conference", "langue", "traduction"], oddsDenominator: 800, category: "metier", estimate: true },
  { id: "px1-correcteur", label: "Devenir correcteur-relecteur", keywords: ["correcteur", "relecteur", "texte", "edition"], oddsDenominator: 500, category: "metier", estimate: true },
  { id: "px1-journaliste", label: "Devenir journaliste", keywords: ["journaliste", "presse", "article", "media"], oddsDenominator: 800, category: "metier", estimate: true },
  { id: "px1-reporter", label: "Devenir reporter de terrain", keywords: ["reporter", "terrain", "reportage", "media"], oddsDenominator: 1200, category: "metier", estimate: true },
  { id: "px1-realisateur", label: "Devenir realisateur de cinema", keywords: ["realisateur", "cinema", "film", "tournage"], oddsDenominator: 4000, category: "artiste", estimate: true },
  { id: "px1-producteur-cinema", label: "Devenir producteur de cinema", keywords: ["producteur", "cinema", "film", "production"], oddsDenominator: 3000, category: "entrepreneuriat", estimate: true },
  { id: "px1-galeriste", label: "Devenir galeriste d'art", keywords: ["galeriste", "galerie", "art", "exposition"], oddsDenominator: 1200, category: "entrepreneuriat", estimate: true },
  { id: "px1-commissaire-priseur", label: "Devenir commissaire-priseur", keywords: ["commissaire", "priseur", "vente", "enchere"], oddsDenominator: 1500, category: "metier", estimate: true },
  { id: "px1-expert-art", label: "Devenir expert en oeuvres d'art", keywords: ["expert", "art", "oeuvre", "estimation"], oddsDenominator: 1500, category: "metier", estimate: true },
  { id: "px1-conservateur-musee", label: "Devenir conservateur de musee", keywords: ["conservateur", "musee", "collection", "patrimoine"], oddsDenominator: 2000, category: "metier", estimate: true },
  { id: "px1-archiviste", label: "Devenir archiviste", keywords: ["archiviste", "archive", "document", "fonds"], oddsDenominator: 500, category: "metier", estimate: true },
  { id: "px1-bibliothecaire", label: "Devenir bibliothecaire", keywords: ["bibliothecaire", "livre", "bibliotheque", "lecture"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-libraire", label: "Devenir libraire independant", keywords: ["libraire", "librairie", "livre", "boutique"], oddsDenominator: 350, category: "entrepreneuriat", estimate: true },
  { id: "px1-bouquiniste", label: "Devenir bouquiniste", keywords: ["bouquiniste", "livre", "ancien", "quai"], oddsDenominator: 600, category: "metier", estimate: true },
  { id: "px1-editeur", label: "Devenir editeur independant", keywords: ["editeur", "edition", "livre", "maison"], oddsDenominator: 1500, category: "entrepreneuriat", estimate: true },
  { id: "px1-imprimeur", label: "Devenir imprimeur", keywords: ["imprimeur", "imprimerie", "impression", "papier"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-serigraphe", label: "Devenir serigraphe", keywords: ["serigraphe", "serigraphie", "impression", "textile"], oddsDenominator: 350, category: "metier", estimate: true },
  { id: "px1-papetier-artisanal", label: "Devenir fabricant de papier artisanal", keywords: ["papetier", "papier", "artisanal", "fibre"], oddsDenominator: 1200, category: "metier", estimate: true },
  { id: "px1-cartographe", label: "Devenir cartographe", keywords: ["cartographe", "carte", "geographie", "plan"], oddsDenominator: 800, category: "metier", estimate: true },
  { id: "px1-topographe", label: "Devenir topographe", keywords: ["topographe", "terrain", "mesure", "releve"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-geologue", label: "Devenir geologue", keywords: ["geologue", "roche", "sol", "terrain"], oddsDenominator: 700, category: "metier", estimate: true },
  { id: "px1-meteorologue", label: "Devenir meteorologue", keywords: ["meteorologue", "meteo", "climat", "prevision"], oddsDenominator: 800, category: "metier", estimate: true },
  { id: "px1-oceanographe", label: "Devenir oceanographe", keywords: ["oceanographe", "ocean", "mer", "recherche"], oddsDenominator: 1200, category: "metier", estimate: true },
  { id: "px1-volcanologue", label: "Devenir volcanologue", keywords: ["volcanologue", "volcan", "lave", "recherche"], oddsDenominator: 2000, category: "metier", estimate: true },
  { id: "px1-astronome", label: "Devenir astronome", keywords: ["astronome", "etoile", "telescope", "recherche"], oddsDenominator: 2500, category: "metier", estimate: true },
  { id: "px1-chercheur-cnrs", label: "Devenir chercheur au CNRS", keywords: ["chercheur", "cnrs", "recherche", "science"], oddsDenominator: 1500, category: "metier", estimate: true },
  { id: "px1-enseignant-chercheur", label: "Devenir enseignant-chercheur titulaire", keywords: ["enseignant", "chercheur", "universite", "titulaire"], oddsDenominator: 1200, category: "metier", estimate: true },
  { id: "px1-prof-fac", label: "Devenir professeur des universites", keywords: ["professeur", "universite", "faculte", "recherche"], oddsDenominator: 2000, category: "metier", estimate: true },
  { id: "px1-prof-agrege", label: "Devenir professeur agrege", keywords: ["professeur", "agrege", "concours", "lycee"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-instituteur", label: "Devenir professeur des ecoles", keywords: ["instituteur", "ecole", "enfant", "classe"], oddsDenominator: 150, category: "metier", estimate: true },
  { id: "px1-orthopedagogue", label: "Devenir orthopedagogue", keywords: ["orthopedagogue", "apprentissage", "enfant", "soutien"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-educateur-specialise", label: "Devenir educateur specialise", keywords: ["educateur", "specialise", "social", "accompagnement"], oddsDenominator: 120, category: "metier", estimate: true },
  { id: "px1-assistant-social", label: "Devenir assistant de service social", keywords: ["assistant", "social", "aide", "accompagnement"], oddsDenominator: 130, category: "metier", estimate: true },
  { id: "px1-conseiller-orientation", label: "Devenir conseiller d'orientation", keywords: ["conseiller", "orientation", "etudiant", "metier"], oddsDenominator: 300, category: "metier", estimate: true },
  { id: "px1-coach-professionnel", label: "Devenir coach professionnel certifie", keywords: ["coach", "professionnel", "accompagnement", "carriere"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-formateur-independant", label: "Devenir formateur independant", keywords: ["formateur", "formation", "pedagogie", "independant"], oddsDenominator: 250, category: "metier", estimate: true },
  { id: "px1-consultant-rh", label: "Devenir consultant RH", keywords: ["consultant", "rh", "recrutement", "entreprise"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-chasseur-tetes", label: "Devenir chasseur de tetes", keywords: ["chasseur", "tetes", "recrutement", "cadre"], oddsDenominator: 600, category: "metier", estimate: true },
  { id: "px1-consultant-strategie", label: "Devenir consultant en strategie", keywords: ["consultant", "strategie", "conseil", "entreprise"], oddsDenominator: 800, category: "metier", estimate: true },
  { id: "px1-mediateur", label: "Devenir mediateur professionnel", keywords: ["mediateur", "conflit", "dialogue", "accord"], oddsDenominator: 500, category: "metier", estimate: true },
  { id: "px1-detective-prive", label: "Devenir detective prive", keywords: ["detective", "prive", "enquete", "filature"], oddsDenominator: 700, category: "metier", estimate: true },
  { id: "px1-agent-securite", label: "Devenir agent de securite", keywords: ["agent", "securite", "surveillance", "garde"], oddsDenominator: 80, category: "metier", estimate: true },
  { id: "px1-maitre-chien", label: "Devenir maitre-chien", keywords: ["maitre", "chien", "securite", "dressage"], oddsDenominator: 300, category: "metier", estimate: true },
  { id: "px1-pompier-pro", label: "Devenir sapeur-pompier professionnel", keywords: ["pompier", "incendie", "secours", "caserne"], oddsDenominator: 250, category: "metier", estimate: true },
  { id: "px1-policier", label: "Devenir gardien de la paix", keywords: ["policier", "police", "securite", "ordre"], oddsDenominator: 150, category: "metier", estimate: true },
  { id: "px1-gendarme", label: "Devenir gendarme", keywords: ["gendarme", "gendarmerie", "securite", "brigade"], oddsDenominator: 150, category: "metier", estimate: true },
  { id: "px1-douanier", label: "Devenir douanier", keywords: ["douanier", "douane", "frontiere", "controle"], oddsDenominator: 200, category: "metier", estimate: true },
  { id: "px1-maitre-nageur", label: "Devenir maitre-nageur sauveteur", keywords: ["maitre", "nageur", "piscine", "sauvetage"], oddsDenominator: 200, category: "metier", estimate: true },
  { id: "px1-secouriste-mer", label: "Devenir sauveteur en mer", keywords: ["sauveteur", "mer", "secours", "plage"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-restaurateur-bistrot", label: "Ouvrir un bistrot de quartier", keywords: ["restaurateur", "bistrot", "quartier", "cuisine"], oddsDenominator: 200, category: "entrepreneuriat", estimate: true },
  { id: "px1-chef-etoile", label: "Devenir chef etoile", keywords: ["chef", "etoile", "gastronomie", "restaurant"], oddsDenominator: 3000, category: "metier", estimate: true },
  { id: "px1-chef-cuisine", label: "Devenir chef de cuisine", keywords: ["chef", "cuisine", "restaurant", "brigade"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-chef-particulier", label: "Devenir chef a domicile", keywords: ["chef", "domicile", "particulier", "cuisine"], oddsDenominator: 350, category: "metier", estimate: true },
  { id: "px1-cuisinier-collectivite", label: "Devenir cuisinier en collectivite", keywords: ["cuisinier", "collectivite", "cantine", "cuisine"], oddsDenominator: 100, category: "metier", estimate: true },
  { id: "px1-charcutier-traiteur", label: "Devenir charcutier-traiteur", keywords: ["charcutier", "traiteur", "viande", "boutique"], oddsDenominator: 250, category: "metier", estimate: true },
  { id: "px1-rotisseur", label: "Devenir rotisseur", keywords: ["rotisseur", "poulet", "rotisserie", "marche"], oddsDenominator: 300, category: "metier", estimate: true },
  { id: "px1-creperie", label: "Ouvrir une creperie", keywords: ["crepier", "creperie", "galette", "restaurant"], oddsDenominator: 200, category: "entrepreneuriat", estimate: true },
  { id: "px1-pizzaiolo", label: "Devenir pizzaiolo", keywords: ["pizzaiolo", "pizza", "four", "restaurant"], oddsDenominator: 200, category: "metier", estimate: true },
  { id: "px1-food-truck", label: "Lancer un food truck", keywords: ["food", "truck", "ambulant", "cuisine"], oddsDenominator: 250, category: "entrepreneuriat", estimate: true },
  { id: "px1-brasseur-artisanal", label: "Ouvrir une micro-brasserie", keywords: ["brasseur", "micro", "brasserie", "biere"], oddsDenominator: 350, category: "entrepreneuriat", estimate: true },
  { id: "px1-coutelier-art", label: "Devenir coutelier d'art", keywords: ["coutelier", "couteau", "art", "lame"], oddsDenominator: 1000, category: "artiste", estimate: true },
  { id: "px1-verrier-art", label: "Devenir verrier d'art", keywords: ["verrier", "verre", "art", "souffle"], oddsDenominator: 900, category: "artiste", estimate: true },
  { id: "px1-emailleur", label: "Devenir emailleur sur metaux", keywords: ["emailleur", "email", "cuivre", "art"], oddsDenominator: 1000, category: "metier", estimate: true },
  { id: "px1-laqueur", label: "Devenir laqueur d'art", keywords: ["laqueur", "laque", "finition", "art"], oddsDenominator: 1100, category: "metier", estimate: true },
  { id: "px1-restaurateur-tableaux", label: "Devenir restaurateur de tableaux", keywords: ["restaurateur", "tableau", "peinture", "atelier"], oddsDenominator: 1000, category: "metier", estimate: true },
  { id: "px1-restaurateur-ceramique", label: "Devenir restaurateur de ceramiques", keywords: ["restaurateur", "ceramique", "porcelaine", "atelier"], oddsDenominator: 1100, category: "metier", estimate: true },
  { id: "px1-restaurateur-textile", label: "Devenir restaurateur de textiles anciens", keywords: ["restaurateur", "textile", "tapisserie", "atelier"], oddsDenominator: 1200, category: "metier", estimate: true },
  { id: "px1-taxidermiste", label: "Devenir taxidermiste", keywords: ["taxidermiste", "naturalisation", "animal", "atelier"], oddsDenominator: 1000, category: "metier", estimate: true },
  { id: "px1-parfumeur", label: "Devenir parfumeur createur", keywords: ["parfumeur", "parfum", "nez", "fragrance"], oddsDenominator: 2500, category: "metier", estimate: true },
  { id: "px1-savonnier", label: "Devenir savonnier artisanal", keywords: ["savonnier", "savon", "saponification", "atelier"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-bougie-artisanale", label: "Devenir fabricant de bougies artisanales", keywords: ["bougie", "cire", "artisanal", "parfum"], oddsDenominator: 350, category: "entrepreneuriat", estimate: true },
  { id: "px1-cosmetique-bio", label: "Lancer une marque de cosmetique bio", keywords: ["cosmetique", "bio", "creme", "naturel"], oddsDenominator: 600, category: "entrepreneuriat", estimate: true },
  { id: "px1-vannier-osier", label: "Devenir vannier-osiericulteur", keywords: ["vannier", "osier", "culture", "panier"], oddsDenominator: 800, category: "metier", estimate: true },
  { id: "px1-sabotier", label: "Devenir sabotier", keywords: ["sabotier", "sabot", "bois", "artisan"], oddsDenominator: 1500, category: "metier", estimate: true },
  { id: "px1-charron", label: "Devenir charron", keywords: ["charron", "roue", "bois", "charrette"], oddsDenominator: 2000, category: "metier", estimate: true },
  { id: "px1-chaisier", label: "Devenir rempailleur de chaises", keywords: ["rempailleur", "chaise", "paille", "artisan"], oddsDenominator: 900, category: "metier", estimate: true },
  { id: "px1-cannage", label: "Devenir canneur de sieges", keywords: ["canneur", "cannage", "rotin", "siege"], oddsDenominator: 900, category: "metier", estimate: true },
  { id: "px1-restaurateur-horlogerie", label: "Devenir restaurateur de pendules anciennes", keywords: ["restaurateur", "pendule", "horloge", "ancien"], oddsDenominator: 1000, category: "metier", estimate: true },
  { id: "px1-bijoutier", label: "Devenir bijoutier", keywords: ["bijoutier", "bijou", "or", "boutique"], oddsDenominator: 500, category: "metier", estimate: true },
  { id: "px1-lapidaire", label: "Devenir lapidaire", keywords: ["lapidaire", "pierre", "taille", "gemme"], oddsDenominator: 1200, category: "metier", estimate: true },
  { id: "px1-gemmologue", label: "Devenir gemmologue", keywords: ["gemmologue", "pierre", "precieuse", "expertise"], oddsDenominator: 1500, category: "metier", estimate: true },
  { id: "px1-orfevre", label: "Devenir orfevre", keywords: ["orfevre", "argent", "or", "metal"], oddsDenominator: 900, category: "metier", estimate: true },
  { id: "px1-ciseleur", label: "Devenir ciseleur", keywords: ["ciseleur", "metal", "ciselure", "art"], oddsDenominator: 1200, category: "metier", estimate: true },
  { id: "px1-fondeur-cloches", label: "Devenir fondeur de cloches", keywords: ["fondeur", "cloche", "bronze", "fonderie"], oddsDenominator: 3000, category: "metier", estimate: true },
  { id: "px1-campaniste", label: "Devenir campaniste", keywords: ["campaniste", "cloche", "clocher", "entretien"], oddsDenominator: 2500, category: "metier", estimate: true },
  { id: "px1-couvreur-ardoise", label: "Devenir couvreur ardoisier", keywords: ["couvreur", "ardoise", "toit", "toiture"], oddsDenominator: 200, category: "metier", estimate: true },
  { id: "px1-couvreur-chaume", label: "Devenir couvreur chaumier", keywords: ["couvreur", "chaume", "toit", "roseau"], oddsDenominator: 1500, category: "metier", estimate: true },
  { id: "px1-batisseur-pierre-seche", label: "Devenir batisseur en pierre seche", keywords: ["batisseur", "pierre", "seche", "mur"], oddsDenominator: 1000, category: "metier", estimate: true },
  { id: "px1-restaurateur-chateaux", label: "Devenir restaurateur de chateaux", keywords: ["restaurateur", "chateau", "patrimoine", "renovation"], oddsDenominator: 1000, category: "metier", estimate: true },
  { id: "px1-jardinier-paysagiste", label: "Devenir jardinier-paysagiste de jardins historiques", keywords: ["jardinier", "paysagiste", "historique", "parc"], oddsDenominator: 700, category: "metier", estimate: true },
  { id: "px1-elagueur-grimpeur", label: "Devenir elagueur-grimpeur arboriste", keywords: ["elagueur", "arboriste", "grimpeur", "arbre"], oddsDenominator: 250, category: "metier", estimate: true },
  { id: "px1-bottier-orthopediste", label: "Devenir bottier-orthopediste", keywords: ["bottier", "orthopediste", "chaussure", "sur-mesure"], oddsDenominator: 600, category: "metier", estimate: true },
  { id: "px1-orthoprothesiste", label: "Devenir orthoprothesiste", keywords: ["orthoprothesiste", "prothese", "appareillage", "membre"], oddsDenominator: 500, category: "metier", estimate: true },
  { id: "px1-podo-orthesiste", label: "Devenir podo-orthesiste", keywords: ["podo", "orthesiste", "pied", "semelle"], oddsDenominator: 500, category: "metier", estimate: true },
  { id: "px1-occuliste-prothesiste", label: "Devenir oculariste", keywords: ["oculariste", "prothese", "oeil", "artificiel"], oddsDenominator: 2500, category: "metier", estimate: true },
  { id: "px1-audioprothesiste-cabinet", label: "Ouvrir un cabinet d'audioprothese", keywords: ["audioprothesiste", "cabinet", "audition", "appareil"], oddsDenominator: 250, category: "entrepreneuriat", estimate: true },
  { id: "px1-osteopathe-pediatrique", label: "Devenir osteopathe pediatrique", keywords: ["osteopathe", "pediatrique", "bebe", "enfant"], oddsDenominator: 300, category: "metier", estimate: true },
  { id: "px1-sage-femme-echographie", label: "Devenir sage-femme echographiste", keywords: ["sage", "femme", "echographie", "grossesse"], oddsDenominator: 250, category: "metier", estimate: true },
  { id: "px1-doula", label: "Devenir doula", keywords: ["doula", "accompagnement", "naissance", "maternite"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-naturopathe-animalier", label: "Devenir naturopathe animalier", keywords: ["naturopathe", "animalier", "animal", "naturel"], oddsDenominator: 600, category: "metier", estimate: true },
  { id: "px1-phytotherapeute", label: "Devenir phytotherapeute", keywords: ["phytotherapeute", "plante", "soin", "remede"], oddsDenominator: 500, category: "metier", estimate: true },
  { id: "px1-aromatherapeute", label: "Devenir aromatherapeute", keywords: ["aromatherapeute", "huile", "essentielle", "soin"], oddsDenominator: 500, category: "metier", estimate: true },
  { id: "px1-conseiller-funeraire-marbrier", label: "Devenir marbrier funeraire", keywords: ["marbrier", "funeraire", "pierre", "tombe"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-thanatopracteur", label: "Devenir thanatopracteur", keywords: ["thanatopracteur", "soin", "defunt", "funeraire"], oddsDenominator: 500, category: "metier", estimate: true },
  { id: "px1-fossoyeur", label: "Devenir fossoyeur", keywords: ["fossoyeur", "cimetiere", "tombe", "funeraire"], oddsDenominator: 200, category: "metier", estimate: true },
  { id: "px1-horloger-bijoutier", label: "Devenir horloger-bijoutier", keywords: ["horloger", "bijoutier", "montre", "bijou"], oddsDenominator: 500, category: "metier", estimate: true },
  { id: "px1-restaurateur-instruments", label: "Devenir restaurateur d'instruments anciens", keywords: ["restaurateur", "instrument", "ancien", "musique"], oddsDenominator: 1500, category: "metier", estimate: true },
  { id: "px1-archetier", label: "Devenir archetier", keywords: ["archetier", "archet", "violon", "bois"], oddsDenominator: 3000, category: "metier", estimate: true },
  { id: "px1-facteur-anches", label: "Devenir facteur d'instruments a anches", keywords: ["facteur", "anche", "hautbois", "instrument"], oddsDenominator: 2500, category: "metier", estimate: true },
  { id: "px1-restaurateur-vitraux", label: "Devenir restaurateur de vitraux", keywords: ["restaurateur", "vitrail", "verre", "eglise"], oddsDenominator: 1200, category: "metier", estimate: true },
  { id: "px1-fontainier", label: "Devenir fontainier", keywords: ["fontainier", "fontaine", "eau", "reseau"], oddsDenominator: 600, category: "metier", estimate: true },
  { id: "px1-cidriculteur", label: "Devenir cidriculteur fermier", keywords: ["cidriculteur", "pomme", "cidre", "ferme"], oddsDenominator: 500, category: "metier", estimate: true },
  { id: "px1-spiruliniculteur", label: "Devenir producteur de spiruline", keywords: ["spiruline", "algue", "bassin", "production"], oddsDenominator: 700, category: "metier", estimate: true },
  { id: "px1-heliciculteur", label: "Devenir heliciculteur", keywords: ["heliciculteur", "escargot", "elevage", "ferme"], oddsDenominator: 500, category: "metier", estimate: true },
  { id: "px1-eleveur-insectes", label: "Devenir eleveur d'insectes comestibles", keywords: ["eleveur", "insecte", "comestible", "elevage"], oddsDenominator: 800, category: "entrepreneuriat", estimate: true },
  { id: "px1-aquaculteur", label: "Devenir aquaculteur", keywords: ["aquaculteur", "poisson", "elevage", "bassin"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-algoculteur", label: "Devenir algoculteur", keywords: ["algoculteur", "algue", "mer", "recolte"], oddsDenominator: 700, category: "metier", estimate: true },
  { id: "px1-cressiculteur", label: "Devenir cressiculteur", keywords: ["cressiculteur", "cresson", "fontaine", "culture"], oddsDenominator: 800, category: "metier", estimate: true },
  { id: "px1-champignonniste", label: "Devenir champignonniste", keywords: ["champignonniste", "champignon", "cave", "culture"], oddsDenominator: 500, category: "metier", estimate: true },
  { id: "px1-asperge-producteur", label: "Devenir producteur d'asperges", keywords: ["asperge", "producteur", "culture", "primeur"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-tabaculteur", label: "Devenir producteur de plantes a infusion", keywords: ["producteur", "infusion", "plante", "tisane"], oddsDenominator: 600, category: "metier", estimate: true },
  { id: "px1-rosieriste", label: "Devenir rosieriste", keywords: ["rosieriste", "rose", "rosier", "culture"], oddsDenominator: 700, category: "metier", estimate: true },
  { id: "px1-bonsai", label: "Devenir producteur de bonsais", keywords: ["bonsai", "arbre", "miniature", "culture"], oddsDenominator: 800, category: "metier", estimate: true },
  { id: "px1-restaurateur-livres", label: "Devenir restaurateur de livres anciens", keywords: ["restaurateur", "livre", "ancien", "reliure"], oddsDenominator: 1200, category: "metier", estimate: true },
  { id: "px1-doreur-tranche", label: "Devenir doreur sur tranche", keywords: ["doreur", "tranche", "livre", "or"], oddsDenominator: 2000, category: "metier", estimate: true },
  { id: "px1-restaurateur-photographies", label: "Devenir restaurateur de photographies anciennes", keywords: ["restaurateur", "photographie", "ancien", "image"], oddsDenominator: 1500, category: "metier", estimate: true },
  { id: "px1-conseil-image", label: "Devenir conseiller en image", keywords: ["conseiller", "image", "relooking", "style"], oddsDenominator: 500, category: "metier", estimate: true },
  { id: "px1-home-stager", label: "Devenir home stager", keywords: ["home", "stager", "valorisation", "immobilier"], oddsDenominator: 400, category: "metier", estimate: true },
  { id: "px1-organisateur-mariage", label: "Devenir organisateur de mariages", keywords: ["organisateur", "mariage", "evenement", "wedding"], oddsDenominator: 400, category: "entrepreneuriat", estimate: true },
  { id: "px1-organisateur-evenements", label: "Devenir organisateur d'evenements", keywords: ["organisateur", "evenement", "reception", "logistique"], oddsDenominator: 350, category: "entrepreneuriat", estimate: true },
  { id: "px1-coach-vocal", label: "Devenir coach vocal", keywords: ["coach", "vocal", "chant", "voix"], oddsDenominator: 600, category: "metier", estimate: true },
  { id: "px1-prof-equitation", label: "Devenir enseignant d'equitation", keywords: ["enseignant", "equitation", "cheval", "club"], oddsDenominator: 300, category: "metier", estimate: true },
  { id: "px1-palefrenier", label: "Devenir palefrenier soigneur", keywords: ["palefrenier", "cheval", "ecurie", "soin"], oddsDenominator: 200, category: "metier", estimate: true },
  { id: "px1-jockey", label: "Devenir jockey professionnel", keywords: ["jockey", "course", "cheval", "hippodrome"], oddsDenominator: 2000, category: "sport", estimate: true },
  { id: "px1-entraineur-chevaux", label: "Devenir entraineur de chevaux de course", keywords: ["entraineur", "cheval", "course", "ecurie"], oddsDenominator: 1500, category: "metier", estimate: true },
  { id: "px1-naisseur-chevaux", label: "Devenir naisseur-eleveur de chevaux", keywords: ["naisseur", "eleveur", "cheval", "haras"], oddsDenominator: 1200, category: "metier", estimate: true },
];
