import type { Axis, CatalogEntry } from "./types";
import { CATALOG_EXTRA } from "./catalog.extra";
import { CATALOG_ABSURDE } from "./catalog.absurde";
import { CATALOG_CRINGE_1 } from "./catalog.cringe1";
import { CATALOG_CRINGE_2 } from "./catalog.cringe2";
import { CATALOG_CRINGE_3 } from "./catalog.cringe3";
import { CATALOG_CRINGE_4 } from "./catalog.cringe4";
import { CATALOG_CRINGE_5 } from "./catalog.cringe5";
import { CATALOG_CRINGE_6 } from "./catalog.cringe6";

// =============================================================================
// CATALOGUE « Mieux que le Loto »
// -----------------------------------------------------------------------------
// Chaque entrée = une activité avec sa probabilité honnête de rendre millionnaire.
// `oddsDenominator` = « 1 chance sur N ». Sources publiques citées quand possible,
// sinon `estimate: true` + estimation argumentée. Le champ `axes` active
// l'expander (lib/expander.ts) qui module la proba selon le lieu, la
// spécialisation, l'échelle, le format et le stade — voir CATALOG.md.
//
// Pour ajouter une entrée : voir CATALOG.md.
// =============================================================================

const CATALOG_CORE: CatalogEntry[] = [
  // ---------------------------------------------------------------------------
  // HASARD / JEUX
  // ---------------------------------------------------------------------------
  {
    id: "loto-france",
    label: "Gagner le jackpot au Loto (FDJ)",
    keywords: ["loto", "fdj", "jackpot", "tirage", "grille", "française des jeux", "loterie"],
    oddsNumerator: 1,
    oddsDenominator: 19_068_840,
    category: "hasard",
    source: "FDJ — règlement Loto (combinaison gagnante de rang 1)",
  },
  {
    id: "euromillions",
    label: "Gagner le jackpot à l'EuroMillions",
    keywords: ["euromillions", "euromillion", "euro millions", "jackpot", "tirage", "loterie europe"],
    oddsNumerator: 1,
    oddsDenominator: 139_838_160,
    category: "hasard",
    source: "EuroMillions — règlement officiel (rang 1)",
  },
  {
    id: "mymillion",
    label: "Gagner avec le code MyMillion (EuroMillions)",
    keywords: ["mymillion", "my million", "code", "millionnaire fdj", "tirage", "euromillions code"],
    oddsNumerator: 1,
    oddsDenominator: 5_000_000,
    category: "hasard",
    source: "FDJ — un code MyMillion garanti gagnant par tirage EuroMillions",
  },
  {
    id: "scratch-ticket",
    label: "Devenir millionnaire avec un ticket à gratter",
    keywords: ["ticket", "gratter", "grattage", "scratch", "millionnaire", "fdj", "morpion", "cash"],
    oddsNumerator: 1,
    oddsDenominator: 3_000_000,
    category: "hasard",
    source: "FDJ — gains maximum jeux de grattage (estimation lots top)",
    estimate: true,
  },
  {
    id: "keno",
    label: "Toucher le gros lot au Keno",
    keywords: ["keno", "tirage", "loterie", "numero"],
    oddsNumerator: 1,
    oddsDenominator: 2_147_181,
    category: "hasard",
    source: "FDJ — Keno (10 numéros)",
  },
  {
    id: "casino-roulette",
    label: "Devenir riche à la roulette du casino",
    keywords: ["casino", "roulette", "rouge", "noir", "plein", "martingale", "jeux argent"],
    oddsNumerator: 1,
    oddsDenominator: 500_000,
    category: "hasard",
    estimate: true,
  },
  {
    id: "poker-tournoi",
    label: "Gagner un gros tournoi de poker (type WSOP)",
    keywords: ["poker", "tournoi", "wsop", "cartes", "bluff", "texas holdem", "main"],
    oddsNumerator: 1,
    oddsDenominator: 800_000,
    category: "hasard",
    estimate: true,
  },
  {
    id: "paris-sportifs",
    label: "Devenir millionnaire avec les paris sportifs",
    keywords: ["pari", "paris sportifs", "betting", "bookmaker", "cote", "foot", "combine", "winamax", "betclic"],
    oddsNumerator: 1,
    oddsDenominator: 50_000,
    category: "hasard",
    estimate: true,
  },
  {
    id: "tirage-cailloux",
    label: "Trouver un million en tirant des cailloux au hasard",
    keywords: ["cailloux", "caillou", "pierre", "hasard", "pile ou face", "des", "lancer"],
    oddsNumerator: 1,
    oddsDenominator: 50_000_000,
    category: "hasard",
    estimate: true,
  },
  {
    id: "heritage-inattendu",
    label: "Hériter d'un oncle d'Amérique inconnu",
    keywords: ["heritage", "heriter", "oncle", "testament", "succession", "tante", "legs"],
    oddsNumerator: 1,
    oddsDenominator: 1_000_000,
    category: "hasard",
    estimate: true,
  },
  {
    id: "trouver-tresor",
    label: "Trouver un trésor enfoui avec un détecteur de métaux",
    keywords: ["tresor", "detecteur", "metaux", "fouille", "or", "pieces", "trouvaille"],
    oddsNumerator: 1,
    oddsDenominator: 2_000_000,
    category: "hasard",
    estimate: true,
  },

  // ---------------------------------------------------------------------------
  // INVESTISSEMENT
  // ---------------------------------------------------------------------------
  {
    id: "sp500-30ans",
    label: "Épargner sur le S&P 500 pendant 30 ans",
    keywords: ["bourse", "sp500", "s&p 500", "etf", "epargne", "indice", "investir long terme", "pea", "actions", "placement"],
    oddsNumerator: 1,
    oddsDenominator: 3,
    category: "investissement",
    source: "Rendement historique ~7%/an réel ; effort d'épargne régulier sur 30 ans",
    estimate: true,
    axes: ["echelle"],
  },
  {
    id: "immobilier-france-10ans",
    label: "Investir dans l'immobilier en France (10 ans, +20%)",
    keywords: ["immobilier", "appartement", "maison", "locatif", "pierre", "investissement immo", "loyer", "bien", "achat"],
    oddsNumerator: 1,
    oddsDenominator: 2,
    category: "investissement",
    source: "Notaires de France — appréciation moyenne + effet levier crédit",
    estimate: true,
    axes: ["lieu", "echelle"],
  },
  {
    id: "crypto-holder-10ans",
    label: "Hodler des cryptos pendant 10 ans",
    keywords: ["crypto", "bitcoin", "btc", "ethereum", "hodl", "holder", "blockchain", "altcoin", "wallet", "satoshi"],
    oddsNumerator: 1,
    oddsDenominator: 100,
    category: "investissement",
    estimate: true,
    axes: ["echelle"],
  },
  {
    id: "trading-retail-solo",
    label: "Vivre du trading en day-trading solo",
    keywords: ["trading", "trader", "day trading", "scalping", "forex", "cfd", "bourse active", "spéculation"],
    oddsNumerator: 1,
    oddsDenominator: 10_000,
    category: "investissement",
    source: "AMF — ~89% des traders particuliers perdent de l'argent",
  },
  {
    id: "business-angel",
    label: "Devenir business angel et toucher le jackpot",
    keywords: ["angel", "investisseur providentiel", "startup investing", "capital risque", "ticket amorçage", "providentiel"],
    oddsNumerator: 1,
    oddsDenominator: 500,
    category: "investissement",
    estimate: true,
  },
  {
    id: "vc-fund",
    label: "Lancer un fonds de capital-risque",
    keywords: ["venture capital", "vc", "fonds", "capital risque", "lp", "gp", "investissement startup"],
    oddsNumerator: 1,
    oddsDenominator: 50,
    category: "investissement",
    estimate: true,
  },
  {
    id: "assurance-vie",
    label: "Devenir millionnaire via l'assurance-vie fonds euros",
    keywords: ["assurance vie", "fonds euros", "epargne", "rente", "placement sécurisé", "contrat"],
    oddsNumerator: 1,
    oddsDenominator: 8,
    category: "investissement",
    estimate: true,
  },
  {
    id: "or-metaux",
    label: "Investir dans l'or physique sur le long terme",
    keywords: ["or", "lingot", "metaux precieux", "argent metal", "refuge", "napoleon", "once"],
    oddsNumerator: 1,
    oddsDenominator: 30,
    category: "investissement",
    estimate: true,
  },
  {
    id: "scpi",
    label: "Construire un patrimoine via les SCPI",
    keywords: ["scpi", "pierre papier", "immobilier locatif", "rendement", "parts", "rente immo"],
    oddsNumerator: 1,
    oddsDenominator: 15,
    category: "investissement",
    estimate: true,
  },
  {
    id: "nft-flip",
    label: "Faire fortune en flippant des NFT",
    keywords: ["nft", "jpeg", "opensea", "mint", "flip", "collection", "token", "art numérique"],
    oddsNumerator: 1,
    oddsDenominator: 20_000,
    category: "investissement",
    estimate: true,
  },

  // ---------------------------------------------------------------------------
  // ENTREPRENEURIAT — commerces & services « du quotidien »
  // ---------------------------------------------------------------------------
  {
    id: "creer-entreprise",
    label: "Créer son entreprise / monter sa boîte",
    keywords: ["entreprise", "business", "boite", "boîte", "société", "societe", "entrepreneur", "se mettre à son compte", "créer son entreprise", "monter une boite", "auto entrepreneur", "startup"],
    oddsNumerator: 1,
    oddsDenominator: 30,
    category: "entrepreneuriat",
    source: "INSEE — taux de survie & rentabilité des entreprises créées",
    estimate: true,
    axes: ["specialisation", "echelle"],
  },
  {
    id: "commerce-5ans",
    label: "Ouvrir un commerce qui tient 5 ans et reste rentable",
    keywords: ["commerce", "boutique", "magasin", "ouvrir", "entreprise", "rentable", "fonds de commerce"],
    oddsNumerator: 1,
    oddsDenominator: 30,
    category: "entrepreneuriat",
    source: "INSEE — taux de survie à 5 ans des entreprises (~60%) pondéré rentabilité",
    estimate: true,
    axes: ["lieu", "echelle"],
  },
  {
    id: "boulangerie",
    label: "Ouvrir une boulangerie rentable qui dure 5 ans",
    keywords: ["boulangerie", "boulanger", "patisserie", "patissier", "pain", "viennoiserie", "fournil", "baguette"],
    oddsNumerator: 1,
    oddsDenominator: 40,
    category: "entrepreneuriat",
    source: "INSEE / CGAD — boulangerie-pâtisserie, survie & marge",
    estimate: true,
    axes: ["lieu", "specialisation"],
  },
  {
    id: "restaurant",
    label: "Ouvrir un restaurant qui réussit",
    keywords: ["restaurant", "resto", "restauration", "cuisine", "chef", "bistrot", "brasserie", "table", "gastronomie"],
    oddsNumerator: 1,
    oddsDenominator: 80,
    category: "entrepreneuriat",
    source: "INSEE — restauration, forte mortalité à 3-5 ans",
    estimate: true,
    axes: ["lieu", "specialisation"],
  },
  {
    id: "food-truck",
    label: "Lancer un food truck à succès",
    keywords: ["food truck", "camion", "street food", "burger", "tacos", "ambulant", "snack roulant"],
    oddsNumerator: 1,
    oddsDenominator: 120,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["lieu", "specialisation"],
  },
  {
    id: "kebab",
    label: "Ouvrir un kebab / snack rentable",
    keywords: ["kebab", "snack", "tacos", "grec", "sandwich", "fast food", "döner"],
    oddsNumerator: 1,
    oddsDenominator: 60,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["lieu"],
  },
  {
    id: "bar-cafe",
    label: "Tenir un bar ou un café qui marche",
    keywords: ["bar", "cafe", "pub", "brasserie", "troquet", "comptoir", "biere", "tabac"],
    oddsNumerator: 1,
    oddsDenominator: 70,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["lieu"],
  },
  {
    id: "coiffeur",
    label: "Ouvrir un salon de coiffure prospère",
    keywords: ["coiffeur", "coiffure", "salon", "barbier", "barber", "cheveux", "coupe"],
    oddsNumerator: 1,
    oddsDenominator: 90,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["lieu", "specialisation"],
  },
  {
    id: "tatoueur",
    label: "Vivre richement du tatouage",
    keywords: ["tatoueur", "tatouage", "tattoo", "encre", "studio tattoo", "perçage"],
    oddsNumerator: 1,
    oddsDenominator: 200,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["lieu", "specialisation"],
  },
  {
    id: "salle-sport",
    label: "Ouvrir une salle de sport / box de crossfit",
    keywords: ["salle de sport", "fitness", "musculation", "crossfit", "gym", "coach", "box"],
    oddsNumerator: 1,
    oddsDenominator: 150,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["lieu", "specialisation"],
  },
  {
    id: "epicerie",
    label: "Tenir une épicerie / supérette rentable",
    keywords: ["epicerie", "superette", "alimentation", "primeur", "commerce de proximité", "magasin"],
    oddsNumerator: 1,
    oddsDenominator: 80,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["lieu"],
  },
  {
    id: "fleuriste",
    label: "Ouvrir une boutique de fleuriste",
    keywords: ["fleuriste", "fleurs", "bouquet", "plantes", "horticulture", "compositions"],
    oddsNumerator: 1,
    oddsDenominator: 130,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["lieu"],
  },
  {
    id: "franchise-mcdo",
    label: "Devenir franchisé McDonald's",
    keywords: ["franchise", "mcdo", "mcdonald", "franchisé", "restauration rapide", "enseigne"],
    oddsNumerator: 1,
    oddsDenominator: 50,
    category: "entrepreneuriat",
    source: "McDonald's France — apport initial élevé, rentabilité réseau",
    estimate: true,
  },
  {
    id: "franchise-generique",
    label: "Ouvrir une franchise (enseigne établie)",
    keywords: ["franchise", "franchisé", "enseigne", "réseau", "concept", "licence de marque"],
    oddsNumerator: 1,
    oddsDenominator: 60,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["lieu", "specialisation"],
  },
  {
    id: "airbnb-host",
    label: "Devenir hôte Airbnb / conciergerie",
    keywords: ["airbnb", "location courte durée", "conciergerie", "meublé", "host", "saisonnier", "booking"],
    oddsNumerator: 1,
    oddsDenominator: 500,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["lieu", "echelle"],
  },
  {
    id: "artisan-batiment",
    label: "Monter une entreprise du bâtiment (artisan)",
    keywords: ["artisan", "batiment", "btp", "plombier", "electricien", "macon", "menuisier", "renovation", "chantier", "carreleur", "platrier"],
    oddsNumerator: 1,
    oddsDenominator: 100,
    category: "entrepreneuriat",
    source: "INSEE / CAPEB — artisanat du bâtiment",
    estimate: true,
    axes: ["lieu", "echelle"],
  },
  {
    id: "agence-immo",
    label: "Ouvrir une agence immobilière",
    keywords: ["agence immobiliere", "agent immobilier", "mandataire", "transaction", "négociateur", "immo"],
    oddsNumerator: 1,
    oddsDenominator: 80,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["lieu"],
  },

  // ---------------------------------------------------------------------------
  // ENTREPRENEURIAT — tech & scale
  // ---------------------------------------------------------------------------
  {
    id: "startup-unicorn",
    label: "Bâtir une startup licorne (valo > 1 Md$)",
    keywords: ["startup", "licorne", "unicorn", "levée de fonds", "scale up", "tech", "fondateur", "ipo", "valorisation"],
    oddsNumerator: 1,
    oddsDenominator: 1_000_000,
    category: "entrepreneuriat",
    source: "CB Insights — fréquence des licornes parmi les startups financées",
    estimate: true,
  },
  {
    id: "startup-exit-1m",
    label: "Créer une startup et la revendre 1 M€+",
    keywords: ["startup", "exit", "revente", "rachat", "acquisition", "fondateur", "créer entreprise tech", "scale"],
    oddsNumerator: 1,
    oddsDenominator: 1_000,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["specialisation"],
  },
  {
    id: "saas-solo",
    label: "Lancer un SaaS en solo (indie hacker)",
    keywords: ["saas", "logiciel", "abonnement", "indie hacker", "micro saas", "bootstrap", "app web", "outil en ligne", "software"],
    oddsNumerator: 1,
    oddsDenominator: 200,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["specialisation", "echelle"],
  },
  {
    id: "appli-mobile",
    label: "Lancer une application mobile à succès",
    keywords: ["appli", "application", "app", "mobile", "ios", "android", "appstore", "play store", "stationnement", "se garer"],
    oddsNumerator: 1,
    oddsDenominator: 5_000,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["specialisation"],
  },
  {
    id: "ecommerce",
    label: "Lancer une boutique e-commerce rentable",
    keywords: ["ecommerce", "e-commerce", "boutique en ligne", "shopify", "vente en ligne", "dropshipping", "marchand", "panier"],
    oddsNumerator: 1,
    oddsDenominator: 300,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["specialisation", "format"],
  },
  {
    id: "dropshipping",
    label: "Faire fortune en dropshipping",
    keywords: ["dropshipping", "dropship", "aliexpress", "boutique sans stock", "ads facebook", "produit gagnant"],
    oddsNumerator: 1,
    oddsDenominator: 2_000,
    category: "entrepreneuriat",
    estimate: true,
  },
  {
    id: "amazon-fba",
    label: "Vendre sur Amazon FBA",
    keywords: ["amazon", "fba", "marketplace", "private label", "vendeur amazon", "marque distributeur"],
    oddsNumerator: 1,
    oddsDenominator: 800,
    category: "entrepreneuriat",
    estimate: true,
  },
  {
    id: "agence-marketing",
    label: "Monter une agence (marketing, web, com)",
    keywords: ["agence", "marketing", "communication", "web agency", "social media", "seo", "publicité", "growth"],
    oddsNumerator: 1,
    oddsDenominator: 150,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["specialisation", "echelle"],
  },
  {
    id: "freelance-tech",
    label: "Devenir freelance tech indépendant",
    keywords: ["freelance", "indépendant", "consultant", "developpeur", "dev", "prestataire", "mission", "tjm", "auto entrepreneur"],
    oddsNumerator: 1,
    oddsDenominator: 400,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["specialisation"],
  },
  {
    id: "startup-ia",
    label: "Créer une startup d'intelligence artificielle",
    keywords: ["ia", "intelligence artificielle", "ai", "machine learning", "llm", "startup ia", "deep learning", "gpt", "modèle"],
    oddsNumerator: 1,
    oddsDenominator: 3_000,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["specialisation"],
  },
  {
    id: "biotech",
    label: "Fonder une biotech / medtech",
    keywords: ["biotech", "medtech", "pharma", "santé", "laboratoire", "molécule", "dispositif médical", "deeptech"],
    oddsNumerator: 1,
    oddsDenominator: 5_000,
    category: "entrepreneuriat",
    estimate: true,
  },

  // ---------------------------------------------------------------------------
  // CRÉATEURS DE CONTENU
  // ---------------------------------------------------------------------------
  {
    id: "youtube-monetise",
    label: "Devenir youtubeur monétisé qui en vit",
    keywords: ["youtube", "youtubeur", "video", "chaine", "monétisation", "vlog", "abonnés", "vues", "creator"],
    oddsNumerator: 1,
    oddsDenominator: 300,
    category: "createur",
    estimate: true,
    axes: ["specialisation"],
  },
  {
    id: "youtube-top1000",
    label: "Entrer dans le top 1000 YouTube France",
    keywords: ["youtube", "top youtube", "millions abonnés", "star youtube", "youtubeur célèbre"],
    oddsNumerator: 1,
    oddsDenominator: 50_000,
    category: "createur",
    estimate: true,
  },
  {
    id: "twitch-top1000",
    label: "Devenir streamer Twitch du top 1000",
    keywords: ["twitch", "stream", "streamer", "live", "gaming", "viewers", "subs", "tchat"],
    oddsNumerator: 1,
    oddsDenominator: 100_000,
    category: "createur",
    estimate: true,
    axes: ["specialisation"],
  },
  {
    id: "tiktok-partenaire",
    label: "Devenir créateur TikTok partenaire / rémunéré",
    keywords: ["tiktok", "tik tok", "vidéo courte", "viral", "danse", "trend", "fyp", "créateur tiktok"],
    oddsNumerator: 1,
    oddsDenominator: 10_000,
    category: "createur",
    estimate: true,
    axes: ["specialisation"],
  },
  {
    id: "instagram-1m",
    label: "Atteindre +1M followers sur Instagram",
    keywords: ["instagram", "insta", "influenceur", "influenceuse", "followers", "stories", "reels", "photo"],
    oddsNumerator: 1,
    oddsDenominator: 100_000,
    category: "createur",
    estimate: true,
    axes: ["specialisation"],
  },
  {
    id: "blog-rentable",
    label: "Tenir un blog rentable",
    keywords: ["blog", "blogueur", "article", "site web contenu", "affiliation", "adsense", "niche blog", "rédaction web"],
    oddsNumerator: 1,
    oddsDenominator: 1_000,
    category: "createur",
    estimate: true,
    axes: ["specialisation", "format"],
  },
  {
    id: "podcast-top",
    label: "Lancer un podcast dans le top des classements",
    keywords: ["podcast", "podcasteur", "audio", "émission", "micro", "spotify", "apple podcasts"],
    oddsNumerator: 1,
    oddsDenominator: 100_000,
    category: "createur",
    estimate: true,
    axes: ["specialisation"],
  },
  {
    id: "onlyfans-top1",
    label: "Entrer dans le top 1% OnlyFans",
    keywords: ["onlyfans", "of", "créatrice", "créateur adulte", "abonnement contenu", "patreon adulte"],
    oddsNumerator: 1,
    oddsDenominator: 100_000,
    category: "createur",
    estimate: true,
  },
  {
    id: "newsletter",
    label: "Monétiser une newsletter à fort lectorat",
    keywords: ["newsletter", "substack", "email", "abonnés payants", "infolettre", "mailing"],
    oddsNumerator: 1,
    oddsDenominator: 2_000,
    category: "createur",
    estimate: true,
    axes: ["specialisation"],
  },
  {
    id: "formateur-en-ligne",
    label: "Vendre des formations en ligne",
    keywords: ["formation", "formateur", "cours en ligne", "infopreneur", "udemy", "coaching", "e-learning", "masterclass"],
    oddsNumerator: 1,
    oddsDenominator: 1_500,
    category: "createur",
    estimate: true,
    axes: ["specialisation"],
  },
  {
    id: "streamer-jeu",
    label: "Devenir créateur gaming / let's player",
    keywords: ["gaming", "jeux vidéo", "let's play", "gameplay", "esport content", "manette", "fortnite", "minecraft"],
    oddsNumerator: 1,
    oddsDenominator: 40_000,
    category: "createur",
    estimate: true,
  },

  // ---------------------------------------------------------------------------
  // ARTISTES
  // ---------------------------------------------------------------------------
  {
    id: "auteur-bestseller",
    label: "Écrire un livre best-seller",
    keywords: ["livre", "auteur", "écrivain", "roman", "best seller", "écrire", "édition", "manuscrit", "publier", "bouquin"],
    oddsNumerator: 1,
    oddsDenominator: 40_000,
    category: "artiste",
    estimate: true,
    axes: ["specialisation"],
  },
  {
    id: "musicien-major",
    label: "Être signé en major et percer dans la musique",
    keywords: ["musicien", "chanteur", "musique", "major", "label", "album", "groupe", "artiste", "rappeur", "rap", "chanson"],
    oddsNumerator: 1,
    oddsDenominator: 50_000,
    category: "artiste",
    estimate: true,
    axes: ["specialisation"],
  },
  {
    id: "dj-international",
    label: "Devenir DJ international",
    keywords: ["dj", "deejay", "mix", "platines", "electro", "techno", "house", "festival", "club"],
    oddsNumerator: 1,
    oddsDenominator: 50_000,
    category: "artiste",
    estimate: true,
  },
  {
    id: "peintre-cote",
    label: "Devenir peintre coté sur le marché de l'art",
    keywords: ["peintre", "peinture", "artiste plasticien", "galerie", "toile", "art contemporain", "exposition", "tableau"],
    oddsNumerator: 1,
    oddsDenominator: 100_000,
    category: "artiste",
    estimate: true,
  },
  {
    id: "realisateur-cine",
    label: "Devenir réalisateur de cinéma reconnu",
    keywords: ["réalisateur", "cinéma", "film", "long métrage", "réaliser", "metteur en scène", "festival cannes"],
    oddsNumerator: 1,
    oddsDenominator: 1_000_000,
    category: "artiste",
    estimate: true,
  },
  {
    id: "comedien-netflix",
    label: "Devenir comédien à l'affiche d'une série Netflix",
    keywords: ["comédien", "acteur", "actrice", "série", "netflix", "casting", "jeu d'acteur", "théâtre", "cinéma"],
    oddsNumerator: 1,
    oddsDenominator: 200_000,
    category: "artiste",
    estimate: true,
  },
  {
    id: "humoriste",
    label: "Percer comme humoriste (one-man-show)",
    keywords: ["humoriste", "humour", "stand up", "one man show", "comique", "blague", "scène", "sketch"],
    oddsNumerator: 1,
    oddsDenominator: 80_000,
    category: "artiste",
    estimate: true,
  },
  {
    id: "photographe",
    label: "Vivre confortablement de la photographie",
    keywords: ["photographe", "photo", "photographie", "studio photo", "shooting", "mariage", "reportage"],
    oddsNumerator: 1,
    oddsDenominator: 3_000,
    category: "artiste",
    estimate: true,
    axes: ["specialisation"],
  },
  {
    id: "illustrateur",
    label: "Vivre de l'illustration / BD",
    keywords: ["illustrateur", "illustration", "bd", "bande dessinée", "dessinateur", "dessin", "manga", "graphiste"],
    oddsNumerator: 1,
    oddsDenominator: 5_000,
    category: "artiste",
    estimate: true,
  },
  {
    id: "danseur",
    label: "Devenir danseur professionnel reconnu",
    keywords: ["danseur", "danse", "ballet", "chorégraphe", "danseuse", "compagnie", "scène"],
    oddsNumerator: 1,
    oddsDenominator: 150_000,
    category: "artiste",
    estimate: true,
  },

  // ---------------------------------------------------------------------------
  // SPORT
  // ---------------------------------------------------------------------------
  {
    id: "footballeur-ligue1",
    label: "Devenir footballeur professionnel en Ligue 1",
    keywords: ["foot", "football", "footballeur", "ligue 1", "joueur pro", "club", "centre de formation", "ballon", "soccer"],
    oddsNumerator: 1,
    oddsDenominator: 100_000,
    category: "sport",
    estimate: true,
  },
  {
    id: "roland-garros",
    label: "Gagner Roland-Garros",
    keywords: ["roland garros", "tennis", "grand chelem", "court", "raquette", "atp", "wta"],
    oddsNumerator: 1,
    oddsDenominator: 10_000_000,
    category: "sport",
    estimate: true,
  },
  {
    id: "tennis-top100",
    label: "Atteindre le top 100 ATP/WTA au tennis",
    keywords: ["tennis", "top 100", "classement atp", "wta", "tennisman", "joueur tennis", "circuit"],
    oddsNumerator: 1,
    oddsDenominator: 1_000_000,
    category: "sport",
    estimate: true,
  },
  {
    id: "tour-de-france",
    label: "Gagner le Tour de France",
    keywords: ["tour de france", "cyclisme", "vélo", "maillot jaune", "coureur", "peloton", "étape"],
    oddsNumerator: 1,
    oddsDenominator: 5_000_000,
    category: "sport",
    estimate: true,
  },
  {
    id: "jo-medaille",
    label: "Décrocher une médaille olympique",
    keywords: ["jo", "jeux olympiques", "médaille", "olympique", "athlète", "podium", "or olympique"],
    oddsNumerator: 1,
    oddsDenominator: 2_000_000,
    category: "sport",
    estimate: true,
  },
  {
    id: "mma-ufc",
    label: "Devenir combattant UFC / MMA pro",
    keywords: ["mma", "ufc", "combat", "octogone", "combattant", "arts martiaux", "free fight", "cage"],
    oddsNumerator: 1,
    oddsDenominator: 500_000,
    category: "sport",
    estimate: true,
  },
  {
    id: "basket-nba",
    label: "Jouer en NBA",
    keywords: ["basket", "nba", "basketball", "panier", "draft", "ballon orange", "dunk"],
    oddsNumerator: 1,
    oddsDenominator: 3_000_000,
    category: "sport",
    estimate: true,
  },
  {
    id: "rugby-pro",
    label: "Devenir rugbyman professionnel (Top 14)",
    keywords: ["rugby", "rugbyman", "top 14", "ovalie", "xv", "mêlée", "ballon ovale"],
    oddsNumerator: 1,
    oddsDenominator: 80_000,
    category: "sport",
    estimate: true,
  },
  {
    id: "esport-pro",
    label: "Devenir joueur e-sport professionnel",
    keywords: ["esport", "e-sport", "gamer pro", "league of legends", "valorant", "cs", "compétition jeu vidéo", "team"],
    oddsNumerator: 1,
    oddsDenominator: 1_000_000,
    category: "sport",
    estimate: true,
  },
  {
    id: "golf-pro",
    label: "Devenir golfeur professionnel sur le circuit",
    keywords: ["golf", "golfeur", "pga", "circuit", "swing", "green", "putt"],
    oddsNumerator: 1,
    oddsDenominator: 800_000,
    category: "sport",
    estimate: true,
  },
  {
    id: "boxe-champion",
    label: "Devenir champion de boxe",
    keywords: ["boxe", "boxeur", "ring", "champion", "poids lourd", "uppercut", "gants"],
    oddsNumerator: 1,
    oddsDenominator: 600_000,
    category: "sport",
    estimate: true,
  },

  // ---------------------------------------------------------------------------
  // MÉTIERS
  // ---------------------------------------------------------------------------
  {
    id: "medecin",
    label: "Devenir médecin (carrière complète)",
    keywords: ["medecin", "médecine", "docteur", "santé", "praticien", "chirurgien", "généraliste", "spécialiste", "hôpital", "pas"],
    oddsNumerator: 1,
    oddsDenominator: 200,
    category: "metier",
    source: "Honoraires moyens + patrimoine constitué sur carrière (estimation)",
    estimate: true,
    axes: ["specialisation"],
  },
  {
    id: "avocat-associe",
    label: "Devenir avocat associé en cabinet",
    keywords: ["avocat", "avocate", "barreau", "cabinet", "associé", "droit", "juriste", "plaidoirie", "robe"],
    oddsNumerator: 1,
    oddsDenominator: 500,
    category: "metier",
    estimate: true,
    axes: ["specialisation"],
  },
  {
    id: "notaire",
    label: "Devenir notaire",
    keywords: ["notaire", "étude notariale", "acte", "succession", "office", "clerc"],
    oddsNumerator: 1,
    oddsDenominator: 300,
    category: "metier",
    estimate: true,
  },
  {
    id: "prof-agrege",
    label: "Devenir professeur agrégé",
    keywords: ["prof", "professeur", "agrégé", "agrégation", "enseignant", "education nationale", "lycée", "concours"],
    oddsNumerator: 1,
    oddsDenominator: 100,
    category: "metier",
    estimate: true,
  },
  {
    id: "pilote-ligne",
    label: "Devenir pilote de ligne",
    keywords: ["pilote", "avion", "aviation", "ligne", "compagnie aérienne", "cockpit", "atpl", "aérien"],
    oddsNumerator: 1,
    oddsDenominator: 2_000,
    category: "metier",
    estimate: true,
  },
  {
    id: "fonctionnaire-a",
    label: "Devenir haut fonctionnaire (catégorie A)",
    keywords: ["fonctionnaire", "fonction publique", "catégorie a", "ena", "administration", "concours", "préfet", "énarque"],
    oddsNumerator: 1,
    oddsDenominator: 50,
    category: "metier",
    estimate: true,
  },
  {
    id: "trader-banque",
    label: "Devenir trader en banque d'investissement",
    keywords: ["trader banque", "salle de marché", "finance", "banque investissement", "bonus", "city", "wall street", "front office"],
    oddsNumerator: 1,
    oddsDenominator: 5_000,
    category: "metier",
    estimate: true,
  },
  {
    id: "dentiste",
    label: "Devenir dentiste / chirurgien-dentiste",
    keywords: ["dentiste", "dentaire", "chirurgien dentiste", "implant", "orthodontiste", "cabinet dentaire", "dents"],
    oddsNumerator: 1,
    oddsDenominator: 150,
    category: "metier",
    estimate: true,
  },
  {
    id: "ingenieur",
    label: "Faire carrière d'ingénieur en tech",
    keywords: ["ingenieur", "ingénieur", "tech", "developpeur senior", "cadre", "informatique", "data", "génie"],
    oddsNumerator: 1,
    oddsDenominator: 800,
    category: "metier",
    estimate: true,
    axes: ["specialisation"],
  },
  {
    id: "expert-comptable",
    label: "Devenir expert-comptable associé",
    keywords: ["expert comptable", "comptabilité", "cabinet comptable", "audit", "commissaire aux comptes", "chiffres"],
    oddsNumerator: 1,
    oddsDenominator: 400,
    category: "metier",
    estimate: true,
  },
  {
    id: "kine",
    label: "Devenir kinésithérapeute libéral",
    keywords: ["kine", "kinésithérapeute", "kiné", "rééducation", "ostéo", "ostéopathe", "cabinet paramédical"],
    oddsNumerator: 1,
    oddsDenominator: 600,
    category: "metier",
    estimate: true,
  },
  {
    id: "pharmacien",
    label: "Devenir pharmacien titulaire d'officine",
    keywords: ["pharmacien", "pharmacie", "officine", "médicaments", "préparateur", "titulaire"],
    oddsNumerator: 1,
    oddsDenominator: 120,
    category: "metier",
    estimate: true,
  },

  // ---------------------------------------------------------------------------
  // SPÉCULATIF / TÉLÉ / POLITIQUE
  // ---------------------------------------------------------------------------
  {
    id: "depute",
    label: "Devenir député",
    keywords: ["député", "politique", "assemblée nationale", "élu", "élection", "mandat", "parlement", "campagne"],
    oddsNumerator: 1,
    oddsDenominator: 100_000,
    category: "speculatif",
    estimate: true,
  },
  {
    id: "maire",
    label: "Devenir maire d'une grande ville",
    keywords: ["maire", "mairie", "municipales", "élu local", "ville", "conseil municipal"],
    oddsNumerator: 1,
    oddsDenominator: 50_000,
    category: "speculatif",
    estimate: true,
  },
  {
    id: "president",
    label: "Devenir Président de la République",
    keywords: ["président", "présidentielle", "élysée", "chef de l'état", "présider", "macron"],
    oddsNumerator: 1,
    oddsDenominator: 30_000_000,
    category: "speculatif",
    estimate: true,
  },
  {
    id: "top-chef",
    label: "Gagner Top Chef",
    keywords: ["top chef", "concours cuisine", "émission cuisine", "candidat", "télé crochet cuisine", "brigade"],
    oddsNumerator: 1,
    oddsDenominator: 2_000_000,
    category: "speculatif",
    estimate: true,
  },
  {
    id: "star-academy",
    label: "Gagner la Star Academy",
    keywords: ["star academy", "télé crochet", "concours chant", "émission tv", "candidat chant", "prime"],
    oddsNumerator: 1,
    oddsDenominator: 5_000_000,
    category: "speculatif",
    estimate: true,
  },
  {
    id: "koh-lanta",
    label: "Gagner Koh-Lanta",
    keywords: ["koh lanta", "aventure", "télé réalité", "épreuve", "poteau", "île", "candidat"],
    oddsNumerator: 1,
    oddsDenominator: 3_000_000,
    category: "speculatif",
    estimate: true,
  },
  {
    id: "the-voice",
    label: "Gagner The Voice",
    keywords: ["the voice", "voix", "concours chant", "coach", "fauteuil", "télé crochet chant"],
    oddsNumerator: 1,
    oddsDenominator: 4_000_000,
    category: "speculatif",
    estimate: true,
  },
  {
    id: "jeu-tv-millionnaire",
    label: "Gagner à un jeu télé (type Qui veut gagner des millions)",
    keywords: ["jeu télé", "millionnaire", "question pour un champion", "qui veut gagner", "quizz", "tf1", "candidat jeu"],
    oddsNumerator: 1,
    oddsDenominator: 1_000_000,
    category: "speculatif",
    estimate: true,
  },
  {
    id: "influenceur-tele-realite",
    label: "Percer via la télé-réalité",
    keywords: ["télé réalité", "candidat", "love island", "marseillais", "anges", "influenceur télé", "réseaux"],
    oddsNumerator: 1,
    oddsDenominator: 80_000,
    category: "speculatif",
    estimate: true,
  },
  {
    id: "epouser-millionnaire",
    label: "Épouser un(e) millionnaire",
    keywords: ["épouser", "mariage", "riche", "millionnaire conjoint", "rencontre", "amour fortune", "beau parti"],
    oddsNumerator: 1,
    oddsDenominator: 5_000,
    category: "speculatif",
    estimate: true,
  },

  // ---------------------------------------------------------------------------
  // MÉTIERS & NICHES VIRAL / DIVERS
  // ---------------------------------------------------------------------------
  {
    id: "coach-sportif",
    label: "Devenir coach sportif / personal trainer",
    keywords: ["coach sportif", "personal trainer", "coaching sport", "préparateur physique", "fitness coach", "remise en forme"],
    oddsNumerator: 1,
    oddsDenominator: 1_500,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["specialisation", "format"],
  },
  {
    id: "coach-dev-perso",
    label: "Devenir coach en développement personnel",
    keywords: ["coach", "développement personnel", "coaching", "mindset", "bien être", "life coach", "mentor"],
    oddsNumerator: 1,
    oddsDenominator: 3_000,
    category: "createur",
    estimate: true,
  },
  {
    id: "vendre-bougies",
    label: "Vendre des bougies / produits artisanaux faits main",
    keywords: ["bougies", "fait main", "artisanat", "etsy", "savon", "cosmétique maison", "créatif", "diy", "macramé"],
    oddsNumerator: 1,
    oddsDenominator: 5_000,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["format"],
  },
  {
    id: "chaine-restauration",
    label: "Bâtir une chaîne de restauration",
    keywords: ["chaine restauration", "concept resto", "réseau restaurant", "déploiement", "multi sites", "groupe"],
    oddsNumerator: 1,
    oddsDenominator: 2_000,
    category: "entrepreneuriat",
    estimate: true,
  },
  {
    id: "agriculteur",
    label: "Devenir agriculteur / exploitant rentable",
    keywords: ["agriculteur", "agriculture", "ferme", "exploitation", "élevage", "vigne", "viticulteur", "champs", "récolte"],
    oddsNumerator: 1,
    oddsDenominator: 200,
    category: "metier",
    estimate: true,
    axes: ["specialisation"],
  },
  {
    id: "viticulteur",
    label: "Produire un grand vin et le vendre cher",
    keywords: ["vin", "viticulteur", "vigne", "domaine", "champagne", "cru", "œnologie", "cave", "bouteille"],
    oddsNumerator: 1,
    oddsDenominator: 1_000,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["lieu"],
  },
  {
    id: "auto-ecole",
    label: "Ouvrir une auto-école",
    keywords: ["auto école", "permis", "conduite", "moniteur", "code de la route", "leçons"],
    oddsNumerator: 1,
    oddsDenominator: 200,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["lieu"],
  },
  {
    id: "garage-auto",
    label: "Ouvrir un garage automobile",
    keywords: ["garage", "mécanicien", "réparation auto", "carrosserie", "voiture", "entretien", "automobile"],
    oddsNumerator: 1,
    oddsDenominator: 150,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["lieu"],
  },
  {
    id: "pressing-laverie",
    label: "Ouvrir un pressing / une laverie automatique",
    keywords: ["pressing", "laverie", "blanchisserie", "nettoyage", "linge", "machine à laver"],
    oddsNumerator: 1,
    oddsDenominator: 120,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["lieu"],
  },
  {
    id: "nounou-creche",
    label: "Ouvrir une micro-crèche",
    keywords: ["crèche", "micro crèche", "garde d'enfants", "nounou", "petite enfance", "assistante maternelle"],
    oddsNumerator: 1,
    oddsDenominator: 300,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["lieu"],
  },
  {
    id: "infirmier-liberal",
    label: "Devenir infirmier(ère) libéral(e)",
    keywords: ["infirmier", "infirmière", "idel", "libéral", "soins", "tournée", "paramédical"],
    oddsNumerator: 1,
    oddsDenominator: 800,
    category: "metier",
    estimate: true,
  },
  {
    id: "veterinaire",
    label: "Ouvrir une clinique vétérinaire",
    keywords: ["vétérinaire", "véto", "animaux", "clinique vétérinaire", "soins animaux", "chien chat"],
    oddsNumerator: 1,
    oddsDenominator: 400,
    category: "metier",
    estimate: true,
  },
  {
    id: "architecte",
    label: "Devenir architecte à son compte",
    keywords: ["architecte", "architecture", "plans", "construction", "maître d'œuvre", "agence archi", "bâtiment design"],
    oddsNumerator: 1,
    oddsDenominator: 1_000,
    category: "metier",
    estimate: true,
  },
  {
    id: "chauffeur-vtc",
    label: "Devenir chauffeur VTC / taxi",
    keywords: ["vtc", "taxi", "chauffeur", "uber", "course", "transport personnes", "voiture avec chauffeur"],
    oddsNumerator: 1,
    oddsDenominator: 8_000,
    category: "metier",
    estimate: true,
    axes: ["echelle"],
  },
  {
    id: "transport-logistique",
    label: "Monter une entreprise de transport / logistique",
    keywords: ["transport", "logistique", "camion", "livraison", "fret", "messagerie", "flotte", "routier"],
    oddsNumerator: 1,
    oddsDenominator: 250,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["echelle"],
  },
  {
    id: "menage-services",
    label: "Lancer une société de ménage / services à domicile",
    keywords: ["ménage", "services à la personne", "aide à domicile", "nettoyage", "femme de ménage", "entretien maison"],
    oddsNumerator: 1,
    oddsDenominator: 400,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["lieu", "echelle"],
  },
  {
    id: "jardinier-paysagiste",
    label: "Devenir paysagiste / jardinier à son compte",
    keywords: ["paysagiste", "jardinier", "jardin", "espaces verts", "tonte", "aménagement extérieur", "végétaux"],
    oddsNumerator: 1,
    oddsDenominator: 600,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["lieu"],
  },
  {
    id: "developpeur-jeux",
    label: "Créer un jeu vidéo indé à succès",
    keywords: ["jeu vidéo", "game dev", "studio jeu", "indé", "steam", "développer jeu", "unity", "unreal", "gamedev"],
    oddsNumerator: 1,
    oddsDenominator: 10_000,
    category: "entrepreneuriat",
    estimate: true,
  },
  {
    id: "inventeur-brevet",
    label: "Inventer un produit et le breveter",
    keywords: ["inventeur", "invention", "brevet", "innovation", "prototype", "gadget", "produit révolutionnaire"],
    oddsNumerator: 1,
    oddsDenominator: 50_000,
    category: "entrepreneuriat",
    estimate: true,
  },
  {
    id: "consultant-strategie",
    label: "Devenir consultant en stratégie / management",
    keywords: ["consultant", "conseil", "stratégie", "management", "cabinet conseil", "mckinsey", "audit conseil"],
    oddsNumerator: 1,
    oddsDenominator: 1_000,
    category: "metier",
    estimate: true,
  },
  {
    id: "trader-crypto",
    label: "Vivre du trading de cryptomonnaies",
    keywords: ["trading crypto", "crypto trader", "altcoin", "leverage", "futures", "scalp crypto", "memecoin", "shitcoin"],
    oddsNumerator: 1,
    oddsDenominator: 15_000,
    category: "investissement",
    estimate: true,
  },
  {
    id: "influenceur-voyage",
    label: "Devenir influenceur voyage / lifestyle",
    keywords: ["voyage", "influenceur voyage", "lifestyle", "globe trotter", "blog voyage", "nomade digital", "travel"],
    oddsNumerator: 1,
    oddsDenominator: 30_000,
    category: "createur",
    estimate: true,
  },
  {
    id: "revendeur-sneakers",
    label: "Faire du reselling (sneakers, hype, cartes)",
    keywords: ["reselling", "sneakers", "revente", "hype", "limited", "cartes pokémon", "drop", "stockx", "revendeur"],
    oddsNumerator: 1,
    oddsDenominator: 4_000,
    category: "entrepreneuriat",
    estimate: true,
  },
  {
    id: "achat-revente-auto",
    label: "Faire de l'achat-revente de voitures",
    keywords: ["achat revente", "voitures", "négoce auto", "marchand de voitures", "occasion", "mandataire auto"],
    oddsNumerator: 1,
    oddsDenominator: 1_500,
    category: "entrepreneuriat",
    estimate: true,
  },
  {
    id: "promoteur-immo",
    label: "Devenir promoteur immobilier",
    keywords: ["promoteur", "promotion immobilière", "programme neuf", "construction logements", "marchand de biens", "foncier"],
    oddsNumerator: 1,
    oddsDenominator: 100,
    category: "investissement",
    estimate: true,
    axes: ["echelle"],
  },
  {
    id: "marchand-de-biens",
    label: "Devenir marchand de biens",
    keywords: ["marchand de biens", "achat revente immo", "rénovation", "plus value", "flip immobilier", "lots"],
    oddsNumerator: 1,
    oddsDenominator: 150,
    category: "investissement",
    estimate: true,
  },
  {
    id: "createur-mode",
    label: "Lancer une marque de vêtements / mode",
    keywords: ["mode", "vêtements", "marque", "streetwear", "textile", "créateur mode", "fringues", "drop mode", "tshirt"],
    oddsNumerator: 1,
    oddsDenominator: 5_000,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["format"],
  },
  {
    id: "createur-cosmetique",
    label: "Lancer une marque de cosmétiques",
    keywords: ["cosmétique", "beauté", "soin", "maquillage", "skincare", "marque beauté", "parfum"],
    oddsNumerator: 1,
    oddsDenominator: 4_000,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["format"],
  },
  {
    id: "brasseur-biere",
    label: "Ouvrir une micro-brasserie",
    keywords: ["brasserie artisanale", "bière", "brasseur", "craft beer", "micro brasserie", "houblon"],
    oddsNumerator: 1,
    oddsDenominator: 800,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["lieu"],
  },
  {
    id: "torréfacteur-cafe",
    label: "Ouvrir un coffee shop / torréfaction",
    keywords: ["coffee shop", "café de spécialité", "torréfaction", "barista", "latte", "grains de café"],
    oddsNumerator: 1,
    oddsDenominator: 600,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["lieu"],
  },
  {
    id: "glacier",
    label: "Ouvrir un glacier artisanal",
    keywords: ["glacier", "glace", "crème glacée", "sorbet", "artisan glacier", "cornet"],
    oddsNumerator: 1,
    oddsDenominator: 400,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["lieu"],
  },
  {
    id: "chocolatier",
    label: "Devenir chocolatier reconnu",
    keywords: ["chocolatier", "chocolat", "confiseur", "praline", "ganache", "artisan chocolatier"],
    oddsNumerator: 1,
    oddsDenominator: 700,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["lieu"],
  },
  {
    id: "traiteur",
    label: "Monter une activité de traiteur / événementiel",
    keywords: ["traiteur", "événementiel", "réception", "buffet", "mariage traiteur", "catering", "banquet"],
    oddsNumerator: 1,
    oddsDenominator: 500,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["lieu"],
  },
  {
    id: "wedding-planner",
    label: "Devenir wedding planner",
    keywords: ["wedding planner", "organisateur mariage", "événement", "cérémonie", "décoration mariage"],
    oddsNumerator: 1,
    oddsDenominator: 2_000,
    category: "entrepreneuriat",
    estimate: true,
  },
  {
    id: "dentellier-luxe",
    label: "Créer une marque de luxe / maroquinerie",
    keywords: ["luxe", "maroquinerie", "sac à main", "haute couture", "marque luxe", "artisanat haut de gamme", "cuir"],
    oddsNumerator: 1,
    oddsDenominator: 20_000,
    category: "entrepreneuriat",
    estimate: true,
  },
  {
    id: "youtubeur-finance",
    label: "Devenir créateur finance / éducation argent",
    keywords: ["finance personnelle", "éducation financière", "investissement contenu", "bourse youtube", "argent contenu", "patrimoine"],
    oddsNumerator: 1,
    oddsDenominator: 8_000,
    category: "createur",
    estimate: true,
  },
  {
    id: "affiliation-seo",
    label: "Vivre de l'affiliation / sites de niche SEO",
    keywords: ["affiliation", "seo", "site de niche", "référencement", "comparateur", "amazon affilié", "trafic google"],
    oddsNumerator: 1,
    oddsDenominator: 3_000,
    category: "createur",
    estimate: true,
  },
  {
    id: "appli-utilitaire",
    label: "Créer une appli utilitaire grand public",
    keywords: ["application utilitaire", "outil mobile", "service appli", "se garer", "parking app", "stationnement", "mobilité"],
    oddsNumerator: 1,
    oddsDenominator: 6_000,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["specialisation"],
  },
  {
    id: "plateforme-marketplace",
    label: "Lancer une marketplace en ligne",
    keywords: ["marketplace", "plateforme", "mise en relation", "place de marché", "commission", "deux faces", "réseau"],
    oddsNumerator: 1,
    oddsDenominator: 4_000,
    category: "entrepreneuriat",
    estimate: true,
  },
  {
    id: "fintech",
    label: "Fonder une fintech",
    keywords: ["fintech", "néobanque", "paiement", "finance tech", "banque en ligne", "crédit tech", "wallet"],
    oddsNumerator: 1,
    oddsDenominator: 8_000,
    category: "entrepreneuriat",
    estimate: true,
  },
  {
    id: "chaine-franchise-perso",
    label: "Franchiser son propre concept",
    keywords: ["franchiser", "concept duplicable", "réseau franchise", "développement enseigne", "tête de réseau"],
    oddsNumerator: 1,
    oddsDenominator: 3_000,
    category: "entrepreneuriat",
    estimate: true,
  },
  {
    id: "rentier-dividendes",
    label: "Devenir rentier grâce aux dividendes",
    keywords: ["rentier", "dividendes", "rente", "revenus passifs", "liberté financière", "fire", "indépendance financière"],
    oddsNumerator: 1,
    oddsDenominator: 200,
    category: "investissement",
    estimate: true,
    axes: ["echelle"],
  },
  {
    id: "trader-options",
    label: "Spéculer sur les options / produits dérivés",
    keywords: ["options", "produits dérivés", "warrants", "turbos", "wall street bets", "calls", "puts", "levier"],
    oddsNumerator: 1,
    oddsDenominator: 12_000,
    category: "investissement",
    estimate: true,
  },
  {
    id: "createur-board-game",
    label: "Créer un jeu de société à succès",
    keywords: ["jeu de société", "board game", "kickstarter jeu", "plateau", "éditeur de jeux", "ludique"],
    oddsNumerator: 1,
    oddsDenominator: 30_000,
    category: "entrepreneuriat",
    estimate: true,
  },
  {
    id: "mannequin",
    label: "Devenir mannequin international",
    keywords: ["mannequin", "mode défilé", "agence mannequin", "top model", "podium", "shooting mode", "égérie"],
    oddsNumerator: 1,
    oddsDenominator: 200_000,
    category: "artiste",
    estimate: true,
  },
  {
    id: "scenariste",
    label: "Devenir scénariste pour le cinéma/séries",
    keywords: ["scénariste", "scénario", "écriture film", "série tv", "dialogues", "fiction", "showrunner"],
    oddsNumerator: 1,
    oddsDenominator: 30_000,
    category: "artiste",
    estimate: true,
  },
  {
    id: "compositeur",
    label: "Devenir compositeur de musiques de films",
    keywords: ["compositeur", "musique de film", "bande originale", "orchestration", "soundtrack", "ost"],
    oddsNumerator: 1,
    oddsDenominator: 100_000,
    category: "artiste",
    estimate: true,
  },
  {
    id: "sculpteur",
    label: "Devenir sculpteur coté",
    keywords: ["sculpteur", "sculpture", "bronze", "marbre", "art statuaire", "atelier sculpture"],
    oddsNumerator: 1,
    oddsDenominator: 150_000,
    category: "artiste",
    estimate: true,
  },
  {
    id: "antiquaire",
    label: "Devenir antiquaire / brocanteur expert",
    keywords: ["antiquaire", "brocante", "antiquités", "objets anciens", "vide grenier", "chineur", "enchères"],
    oddsNumerator: 1,
    oddsDenominator: 3_000,
    category: "entrepreneuriat",
    estimate: true,
  },
  {
    id: "galeriste",
    label: "Ouvrir une galerie d'art",
    keywords: ["galerie d'art", "galeriste", "marché de l'art", "exposition", "vernissage", "œuvres"],
    oddsNumerator: 1,
    oddsDenominator: 5_000,
    category: "entrepreneuriat",
    estimate: true,
  },
  {
    id: "joaillier",
    label: "Devenir joaillier / créateur de bijoux",
    keywords: ["joaillier", "bijoux", "bijouterie", "joaillerie", "diamant", "orfèvre", "création bijou"],
    oddsNumerator: 1,
    oddsDenominator: 4_000,
    category: "entrepreneuriat",
    estimate: true,
  },
  {
    id: "ostreiculteur",
    label: "Devenir ostréiculteur / pêcheur",
    keywords: ["ostréiculteur", "huîtres", "pêcheur", "pêche", "conchyliculture", "bassin", "fruits de mer"],
    oddsNumerator: 1,
    oddsDenominator: 1_500,
    category: "metier",
    estimate: true,
  },
  {
    id: "apiculteur",
    label: "Devenir apiculteur et vendre son miel",
    keywords: ["apiculteur", "miel", "abeilles", "ruches", "apiculture", "essaim"],
    oddsNumerator: 1,
    oddsDenominator: 4_000,
    category: "metier",
    estimate: true,
  },
  {
    id: "dresseur-influenceur-animaux",
    label: "Percer avec un compte animaux viral",
    keywords: ["compte animaux", "chien instagram", "chat viral", "pet influencer", "animal célèbre", "mascotte"],
    oddsNumerator: 1,
    oddsDenominator: 200_000,
    category: "createur",
    estimate: true,
  },
  {
    id: "magicien",
    label: "Devenir magicien / mentaliste reconnu",
    keywords: ["magicien", "magie", "illusionniste", "mentaliste", "tour de magie", "prestidigitation", "spectacle"],
    oddsNumerator: 1,
    oddsDenominator: 80_000,
    category: "artiste",
    estimate: true,
  },
  {
    id: "createur-startup-climat",
    label: "Lancer une startup greentech / climat",
    keywords: ["greentech", "climat", "énergie", "cleantech", "renouvelable", "carbone", "transition écologique", "solaire"],
    oddsNumerator: 1,
    oddsDenominator: 6_000,
    category: "entrepreneuriat",
    estimate: true,
  },
  {
    id: "createur-foncier-data",
    label: "Lancer une startup data / B2B SaaS vertical",
    keywords: ["data", "b2b", "saas vertical", "logiciel métier", "analytics", "donnée", "outil pro"],
    oddsNumerator: 1,
    oddsDenominator: 2_500,
    category: "entrepreneuriat",
    estimate: true,
  },
  {
    id: "createur-robotique",
    label: "Fonder une startup robotique / hardware",
    keywords: ["robotique", "hardware", "robot", "drone", "objet connecté", "iot", "électronique", "matériel"],
    oddsNumerator: 1,
    oddsDenominator: 10_000,
    category: "entrepreneuriat",
    estimate: true,
  },
  {
    id: "createur-spatial",
    label: "Fonder une startup spatiale (newspace)",
    keywords: ["spatial", "fusée", "satellite", "newspace", "espace", "lanceur", "aérospatial"],
    oddsNumerator: 1,
    oddsDenominator: 100_000,
    category: "entrepreneuriat",
    estimate: true,
  },
  {
    id: "pari-loto-foot",
    label: "Gagner gros au Loto Foot",
    keywords: ["loto foot", "pronostic", "grille foot", "13 matchs", "parier foot", "fdj foot"],
    oddsNumerator: 1,
    oddsDenominator: 1_600_000,
    category: "hasard",
    estimate: true,
  },
  {
    id: "pmu-quinté",
    label: "Décrocher le Quinté+ au PMU",
    keywords: ["pmu", "quinté", "courses hippiques", "chevaux", "turf", "tiercé", "hippodrome", "parier chevaux"],
    oddsNumerator: 1,
    oddsDenominator: 1_000_000,
    category: "hasard",
    estimate: true,
  },
  {
    id: "bourse-meme-stock",
    label: "Faire fortune sur une meme stock",
    keywords: ["meme stock", "gamestop", "amc", "short squeeze", "reddit bourse", "wallstreetbets", "action virale"],
    oddsNumerator: 1,
    oddsDenominator: 80_000,
    category: "investissement",
    estimate: true,
  },
  {
    id: "createur-ico-token",
    label: "Lancer son propre token / projet crypto",
    keywords: ["token", "ico", "crypto projet", "blockchain startup", "web3", "dao", "lancer crypto", "tokenomics"],
    oddsNumerator: 1,
    oddsDenominator: 50_000,
    category: "investissement",
    estimate: true,
  },
  {
    id: "createur-ecole-prive",
    label: "Ouvrir une école / organisme de formation privé",
    keywords: ["école privée", "organisme de formation", "centre de formation", "cpf", "enseignement privé", "bootcamp"],
    oddsNumerator: 1,
    oddsDenominator: 1_000,
    category: "entrepreneuriat",
    estimate: true,
  },
  {
    id: "createur-camping",
    label: "Exploiter un camping / hôtellerie de plein air",
    keywords: ["camping", "hôtellerie de plein air", "mobil home", "emplacement", "tourisme", "vacances"],
    oddsNumerator: 1,
    oddsDenominator: 300,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["lieu"],
  },
  {
    id: "createur-hotel",
    label: "Ouvrir un hôtel / chambre d'hôtes",
    keywords: ["hôtel", "chambre d'hôtes", "gîte", "hébergement", "tourisme", "nuitée", "réception hôtel"],
    oddsNumerator: 1,
    oddsDenominator: 250,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["lieu"],
  },
  {
    id: "createur-discotheque",
    label: "Tenir une discothèque / club",
    keywords: ["discothèque", "boîte de nuit", "club", "nightlife", "soirée", "videur", "dancefloor"],
    oddsNumerator: 1,
    oddsDenominator: 500,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["lieu"],
  },
  {
    id: "createur-salle-jeux",
    label: "Ouvrir une salle d'escape game / loisirs",
    keywords: ["escape game", "salle de jeux", "loisirs", "bowling", "laser game", "karting", "divertissement"],
    oddsNumerator: 1,
    oddsDenominator: 400,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["lieu"],
  },
  {
    id: "createur-spa",
    label: "Ouvrir un spa / institut de beauté",
    keywords: ["spa", "institut de beauté", "esthéticienne", "massage", "bien être", "soins esthétiques", "onglerie"],
    oddsNumerator: 1,
    oddsDenominator: 350,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["lieu"],
  },
  {
    id: "createur-pharma-veg",
    label: "Lancer une marque de compléments / nutrition",
    keywords: ["compléments alimentaires", "nutrition", "protéine", "vitamines", "sport nutrition", "superfood", "santé naturelle"],
    oddsNumerator: 1,
    oddsDenominator: 4_000,
    category: "entrepreneuriat",
    estimate: true,
    axes: ["format"],
  },
  {
    id: "createur-app-dating",
    label: "Lancer une appli de rencontre",
    keywords: ["application rencontre", "dating", "tinder like", "match", "rencontres en ligne", "swiper"],
    oddsNumerator: 1,
    oddsDenominator: 12_000,
    category: "entrepreneuriat",
    estimate: true,
  },
  {
    id: "createur-media",
    label: "Lancer un média en ligne",
    keywords: ["média", "journal en ligne", "site d'info", "presse", "magazine", "rédaction", "journalisme web"],
    oddsNumerator: 1,
    oddsDenominator: 5_000,
    category: "createur",
    estimate: true,
  },
  {
    id: "createur-agence-influence",
    label: "Monter une agence d'influenceurs",
    keywords: ["agence influence", "management influenceurs", "talents", "marketing d'influence", "ugc", "créateurs gérés"],
    oddsNumerator: 1,
    oddsDenominator: 2_000,
    category: "entrepreneuriat",
    estimate: true,
  },
  {
    id: "createur-recrutement",
    label: "Monter un cabinet de recrutement / chasse de têtes",
    keywords: ["recrutement", "chasseur de têtes", "rh", "cabinet recrutement", "headhunter", "placement", "talent acquisition"],
    oddsNumerator: 1,
    oddsDenominator: 600,
    category: "entrepreneuriat",
    estimate: true,
  },
  {
    id: "createur-assurance-courtier",
    label: "Devenir courtier (assurance, crédit)",
    keywords: ["courtier", "assurance", "crédit", "mutuelle", "intermédiaire", "courtage", "prêt immobilier"],
    oddsNumerator: 1,
    oddsDenominator: 400,
    category: "metier",
    estimate: true,
  },
  {
    id: "createur-energie-revente",
    label: "Investir dans une centrale solaire / EnR",
    keywords: ["panneaux solaires", "photovoltaïque", "énergie renouvelable", "revente électricité", "centrale solaire", "éolien"],
    oddsNumerator: 1,
    oddsDenominator: 500,
    category: "investissement",
    estimate: true,
  },
  {
    id: "createur-parking",
    label: "Investir dans des places de parking",
    keywords: ["parking", "place de stationnement", "garage box", "investissement parking", "location parking", "se garer"],
    oddsNumerator: 1,
    oddsDenominator: 1_000,
    category: "investissement",
    estimate: true,
    axes: ["lieu", "echelle"],
  },
  {
    id: "createur-foret",
    label: "Investir dans des forêts / groupements forestiers",
    keywords: ["forêt", "groupement forestier", "bois", "sylviculture", "investissement vert", "terres"],
    oddsNumerator: 1,
    oddsDenominator: 40,
    category: "investissement",
    estimate: true,
  },
  {
    id: "createur-cave-vin",
    label: "Investir dans des grands crus / vin de collection",
    keywords: ["vin investissement", "grand cru", "cave à vin", "bordeaux", "spéculation vin", "millésime", "collection vin"],
    oddsNumerator: 1,
    oddsDenominator: 60,
    category: "investissement",
    estimate: true,
  },
  {
    id: "createur-montres",
    label: "Spéculer sur les montres de luxe",
    keywords: ["montres de luxe", "rolex", "patek", "horlogerie", "montre investissement", "collection montres"],
    oddsNumerator: 1,
    oddsDenominator: 2_000,
    category: "investissement",
    estimate: true,
  },
  {
    id: "createur-cartes-collection",
    label: "Spéculer sur les cartes de collection",
    keywords: ["cartes de collection", "pokémon", "magic", "topps", "panini", "tcg", "carte rare", "grading"],
    oddsNumerator: 1,
    oddsDenominator: 30_000,
    category: "investissement",
    estimate: true,
  },
  {
    id: "createur-art-numerique",
    label: "Vivre de l'art numérique / motion design",
    keywords: ["art numérique", "motion design", "3d", "vfx", "infographiste", "design graphique", "blender"],
    oddsNumerator: 1,
    oddsDenominator: 4_000,
    category: "artiste",
    estimate: true,
  },
  {
    id: "createur-voix-off",
    label: "Vivre du doublage / de la voix off",
    keywords: ["voix off", "doublage", "comédien voix", "speaker", "narration", "studio son", "voice over"],
    oddsNumerator: 1,
    oddsDenominator: 8_000,
    category: "artiste",
    estimate: true,
  },
  {
    id: "createur-chaine-asmr",
    label: "Percer avec une niche atypique (ASMR, mukbang…)",
    keywords: ["asmr", "mukbang", "niche atypique", "contenu insolite", "satisfying", "chuchotement", "bizarre viral"],
    oddsNumerator: 1,
    oddsDenominator: 60_000,
    category: "createur",
    estimate: true,
  },
  {
    id: "createur-prof-particulier",
    label: "Vivre des cours particuliers / soutien scolaire",
    keywords: ["cours particuliers", "soutien scolaire", "prof particulier", "tutorat", "acadomia", "aide aux devoirs"],
    oddsNumerator: 1,
    oddsDenominator: 5_000,
    category: "metier",
    estimate: true,
    axes: ["format"],
  },
  {
    id: "createur-naturopathe",
    label: "Devenir naturopathe / thérapeute bien-être",
    keywords: ["naturopathe", "thérapeute", "médecine douce", "sophrologue", "hypnothérapeute", "praticien bien être", "énergéticien"],
    oddsNumerator: 1,
    oddsDenominator: 4_000,
    category: "metier",
    estimate: true,
  },
  {
    id: "createur-detective",
    label: "Devenir détective privé",
    keywords: ["détective", "enquête", "filature", "agence détective", "investigation privée"],
    oddsNumerator: 1,
    oddsDenominator: 3_000,
    category: "metier",
    estimate: true,
  },
  {
    id: "createur-streamer-poker",
    label: "Vivre du poker en ligne",
    keywords: ["poker en ligne", "grinder", "cash game", "mtt", "winamax poker", "pokerstars", "joueur poker"],
    oddsNumerator: 1,
    oddsDenominator: 1_000,
    category: "hasard",
    estimate: true,
  },
];

// Registre absurde complet = ancien catalogue absurde + 6 lots « cringe ».
const ABSURDE_RAW: CatalogEntry[] = [
  ...CATALOG_ABSURDE,
  ...CATALOG_CRINGE_1,
  ...CATALOG_CRINGE_2,
  ...CATALOG_CRINGE_3,
  ...CATALOG_CRINGE_4,
  ...CATALOG_CRINGE_5,
  ...CATALOG_CRINGE_6,
];

// On attribue 2 axes absurdes par entrée (paires rotatives). Les 5 axes
// absurdes restent TOUS applicables au match (cf. matcher) ; ces 2 axes ne
// servent qu'à calibrer l'espace combinatoire (effectiveCount) ≈ 600k. À score
// égal le sérieux gagne, donc l'absurde est concaténé en dernier.
const ABSURDE_AXIS_PAIRS: Axis[][] = [
  ["intensite", "social"],
  ["lieuabsurde", "frequence"],
  ["social", "personne"],
  ["intensite", "lieuabsurde"],
  ["personne", "frequence"],
  ["social", "frequence"],
  ["intensite", "personne"],
  ["lieuabsurde", "personne"],
];

const ABSURDE_WITH_AXES: CatalogEntry[] = ABSURDE_RAW.map((entry, i) => ({
  ...entry,
  axes: entry.axes ?? ABSURDE_AXIS_PAIRS[i % ABSURDE_AXIS_PAIRS.length],
}));

// Catalogue complet = base « cœur » + extension de couverture + registre absurde.
export const CATALOG: CatalogEntry[] = [
  ...CATALOG_CORE,
  ...CATALOG_EXTRA,
  ...ABSURDE_WITH_AXES,
];
